<?php // partial.phtml ?>
<div class="user-panel">
    <div class="pull-left image">
      <!--<img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image" />-->
        <img src="<?php echo $this->basePath('dist/img/manager-xxl.png') ?>" class="user-image" alt="User Image"/> 

    </div>
    <div class="pull-left info">
        <p><?php /* echo $_SESSION['userName']; */ ?></p>

        <a href="#"><i class="fa fa-circle text-success"></i><?php echo $this->translate('Active') ?></a>
    </div>
</div>