<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar " >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            
            <!-- Call uts  -->
            <!--<div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-text-width"></i>
                            <h3 class="box-title">
                                Dashboard
                                <small>Kontrol panel</small>
                            </h3>
                        </div><!-- /.box-header -->
                        <!--<div class="box-body">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div><!-- /.box-body -->
                    <!--</div><!-- /.box -->
                <!--</div><!-- ./col -->
            <!--</div><!-- /.row -->
            <!-- Call Outs end  -->
            
            
            <h1 lang="en">Management Dashboard</h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content">
            
            <!--servisler blok-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box ">
                    <div class="box-header with-border">
                      <h3 class="box-title" lang="en">Services</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool"  id="servisDashboardHesapla"><i class="fa fa-refresh"></i></button>
                        <button id="test-collapse" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                      </div>
                    </div><!-- /.box-header -->
 <div class="box-body" style="display: block;">
                      
                        
                        <form id='actionsForm' method="get" class="form-horizontal">   
                    
                                            
                                            <div class="">
                                                <div id="loading-image-roles" class="input-group">    
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-copyright"></i>
                                                    </div>
                                                    <div id="dropdownRoles" ></div>
                                                </div>
                                                
                                            </div>
                                            <div class="">
                                                <div id="loading-image-roles" class="input-group">    
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-hand-o-right"></i>
                                                    </div>
                                                    <div style="margin-bottom: -10px;width:96%" class="tag-container">
                                                        <ul id="test-cabin" class="tag-box"></ul>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                        <!--<div class="form-group">
                                            <div class="col-sm-10 col-sm-offset-2">
                                                <button id="insertMachineCategory" class="btn btn-primary" type="submit" onclick="return insertActionsWrapper(event);"><i class="fa fa-save"></i>  Action Kaydet </button>
                                                <button id="resetForm" class="btn btn-flat" type="reset" onclick="resetActionsForm();"><i class="fa fa-remove"></i> Reset </button>
                                            </div>
                                        </div>-->
                   
                      
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--servisler blok son-->

            <!-- aftersales dashboard data ana blok -->
            <div class="row">
                <div class="col-lg-4 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_yedek_parca_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p><span lang="en">Spare Part</span></p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-information-circled"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_yedek_parca" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-4 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_yag_container" class="small-box bg-man-ligth-grey bg-green">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Oil</p>
                            
                        </div>
                        <div class="icon">
                            <i class="ion ion-information-circled"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_yag" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-4 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_stok_container" class="small-box bg-man-ligth-grey bg-yellow">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Stock</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-information-circled"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_stok" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->

            </div><!-- /.row -->
            <!-- aftersales dashboard data ana blok son -->
            
            <!--yedek parça (servis içinde onarıma kullanılan) hidden block  -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_yedek_parca_servis_ici" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_yedek_parca_servis_ici_title" lang="en">Service used in repair</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <!--<div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block2_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block2_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>-->
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <!-- yedek parca (servis içinde onarıma kullanılan)(uygun parça) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red" id="1_1">0</h3>
                                    <p lang="en">Eligible Track</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-android-bus"></i>
                                </div>
                                <a onclick="return false;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            <!-- uygun parça ücretli baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text" id="1_2" >0</span>
                                      <span class="info-box-number" lang="en">Paid</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ücretli son.-->
                            <!-- uygun parça garanti baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="1_3">0</span>
                                      <span class="info-box-number" lang="en">Guarantee</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça garanti son.-->
                            <!-- uygun parça toplam baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="1_4">0</span>
                                      <span class="info-box-number" lang="en">Total</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça toplam son.-->
                            <!-- uygun parça OEM baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="1_5">0</span>
                                      <span class="info-box-number" lang="en">OEM</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça OEM son.-->
                            <!-- uygun parça OES baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="1_6">0</span>
                                      <span class="info-box-number" lang="en">OES</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça OES son.-->
                            <!-- uygun parça ESD baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="1_7">0</span>
                                      <span class="info-box-number" lang="en">ESD</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ESD son.-->
                        </div><!-- /.col -->
                        <!-- yedek parca (servis içinde onarıma kullanılan)(uygun parça) son.-->
                        
                        <!-- yedek parca (servis içinde onarıma kullanılan)(Y.S parça) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red" id="t1">0</h3>
                                    <p lang="en">Side Industry Part</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-android-bus"></i>
                                </div>
                                <a onclick="return false;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            <!-- uygun parça ücretli baş.-->
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="2_1">0</span>
                                      <span class="info-box-number" lang="en">Total</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ücretli son.-->                        
                            
                            <!-- Y.S parça Y.san baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="2_2">0</span>
                                      <span class="info-box-number" lang="en">Sub-industry</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça Y.san son.-->
                            <!-- Y.S parça Y.san.my baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="2_3">0</span>
                                      <span class="info-box-number" lang="en">Sub-ind. No Equ</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça Y.san.my son.-->
                            <!-- Y.S parça toplam baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="2_4">0</span>
                                      <span class="info-box-number" lang="en">Total</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça toplam son.-->
                        </div><!-- /.col -->
                        <!-- yedek parca (servis ,ç,nde onarıma kullanılan)(Y.S parça) son.-->
                        
                      </div><!-- /.row -->
                      <div class="row">
                        <div class="col-md-12">
                          
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--yedek parça (servis içinde onarıma kullanılan) hidden blok son-->
            
            <!--yedek parça (servis dışına/direk satılan) hidden block  -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_yedek_parca_servis_disi" style="display: none;">
                    <div class="box-header with-border">
                        <h3 class="box-title" id="panel_yedek_parca_servis_disi_title"><span lang="en">Out of service / sold directly</span></h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <!-- yedek parca (servis içinde onarıma kullanılan)(uygun parça) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <h3 class="man-header-red" id="3_1">0</h3>
                                    <p lang="en">Eligible Track</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-android-arrow-dropright-circle"></i>
                                </div>
                                <a onclick="return false;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            
                            
                            <!-- uygun parça toplam baş.-->
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="3_4">0</span>
                                      <span class="info-box-number" lang="en">Total</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça toplam son.-->
                            <!-- uygun parça OEM baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="3_5">0</span>
                                      <span class="info-box-number" lang="en">OEM</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça OEM son.-->
                            <!-- uygun parça OES baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="3_7">0</span>
                                      <span class="info-box-number" lang="en">OES</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça OES son.-->
                            <!-- uygun parça ESD baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="3_8">0</span>
                                      <span class="info-box-number" lang="en">ESD</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ESD son.-->
                        </div><!-- /.col -->
                        <!-- yedek parca (servis içinde onarıma kullanılan)(uygun parça) son.-->
                        
                        <!-- yedek parca (servis içinde onarıma kullanılan)(Y.S parça) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red" id="t2"></h3>
                                    <p lang="en">Side Industry Part</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-android-arrow-dropright-circle"></i>
                                </div>
                                <a onclick="return false;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            <!-- uygun parça ücretli baş.-->
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="3_9">0</span>
                                      <span class="info-box-number" lang="en">Total</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ücretli son.-->
                            
                            
                            <!-- Y.S parça Y.san baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="3_10">0</span>
                                      <span class="info-box-number" lang="en">Sub-industry</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça Y.san son.-->
                            <!-- Y.S parça Y.san.my baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="3_11">0</span>
                                      <span class="info-box-number" lang="en">Sub-ind. No Equ</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça Y.san.my son.-->
                            <!-- Y.S parça toplam baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="3_12">0</span>
                                      <span class="info-box-number" lang="en">Total</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça toplam son.-->
                        </div><!-- /.col -->
                        <!-- yedek parca (servis ,ç,nde onarıma kullanılan)(Y.S parça) son.-->
                        
                      </div><!-- /.row -->
                      <div class="row">
                        <div class="col-md-12">
                          
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--yedek parça (servis dışına/direk satılan) hidden block son-->
            
            <!--yag  hidden block  -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_yag" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_yag_servis_ici_title" lang="en">Oil</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <!-- yag (servis içinde onarıma kullanılan) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_yag_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red" id="yag1">0</h3>
                                    <p lang="en">Service used in repair</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-wrench"></i>
                                </div>
                                <!--<a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>-->
                            </div>
                            <!-- yag (servis içinde onarıma kullanılan) son.-->
                        </div><!-- /.col -->
                        <!-- yag (servis içinde onarıma kullanılan) son.-->
                        
                        <!-- yag (servis dışına /direk satılan)  baş.-->
                        <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                        <!-- small box -->
                            <div id="servisdisi_yag_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red" id="yag2">0</h3>
                                    <p lang="en">Directly sold out of service</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-wrench"></i>
                                </div>
                                <!--<a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>-->
                            </div>
                        </div><!-- /.col -->
                        <!-- yag (servis dışına /direk satılan) son.-->
                        
                      </div><!-- /.row -->
                      <div class="row">
                        <div class="col-md-12">
                          
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--yag  hidden block son-->
            
            <!--stok  hidden block  -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_stok" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_stok_title" lang="en">Stock</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <!-- stok baş.-->
                        <div class="col-lg-12 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_yag_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red" id="5_1">0</h3>
                                    <p lang="en">Stock Total</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-battery-charging"></i>
                                </div>
                                <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            <!-- stok OEM detay baş.-->
                            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="5_2">0</span>
                                      <span class="info-box-number" lang="en">OES</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- stok OEM detay son.-->
                            <!-- stok OES detay baş.-->
                            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="5_3">0</span>
                                      <span class="info-box-number" lang="en">OEM</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- stok OES detay son.-->
                            <!-- stok ESD detay baş.-->
                            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="5_4">0</span>
                                      <span class="info-box-number" lang="en">ESD</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- stok ESD detay son.-->
                            <!-- stok Y.SAN detay baş.-->
                            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="5_5">0</span>
                                      <span class="info-box-number" lang="en">No Equ</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- stok Y.SAN detay son.-->
                            <!-- stok Y.SAN.MY detay baş.-->
                            <div class="col-lg-2 col-md-2 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text " id="5_6">0</span>
                                      <span class="info-box-number" lang="en">Sub-industry</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description"></span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- stok Y.SAN.MY detay son.-->
                        </div><!-- /.col -->
                        <!-- stok  son.-->

                      </div><!-- /.row -->
                      <div class="row">
                        <div class="col-md-12">
                          
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--stok  hidden block son-->

            <!-- Main row -->
            <div class="row">
            
                <section class="col-lg-6 connectedSortable">

                </section><!-- /.Left col -->
                <!-- right col (We are only adding the ID to make the widgets sortable)-->
                <section class="col-lg-6 connectedSortable">

                </section><!-- right col -->
            </div><!-- /.row (main row) -->

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php /*echo $this->partial('partials/admincontrolasidepartial.phtml');*/ ?>
    <!-- Control Sidebar son-->   
    
</div><!-- ./wrapper -->
<!-- sayfa içine yazılan js'ler ekleniyor-->
<script src="<?php echo $this->basePath('jsinline/dealerowner_faal.js') ?>" type="text/javascript"></script>

 <!-- easyui implementation -->
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/jquery.easyui.min.js') ?>"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/locale/easyui-lang-tr.js') ?>"></script>
<script src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/src/datagrid-filter.js') ?>"></script>

<!-- ddslick select plugin ekleniyor-->
<script src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.js') ?>" type="text/javascript"></script>

<!-- tagCabin Js-->
<script src="<?php echo $this->basePath('plugins/zeynel/tag-cabin/tag-cabin.js') ?>" type="text/javascript"></script>  

<!-- jquery-number plugin-->
<script src="<?php echo $this->basePath('plugins/jquery-number/jquery.number.min.js') ?>" type="text/javascript"></script>

<!-- jquery data-table -->
<script src="<?php echo $this->basePath('plugins/jquery-datatable/datatables.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('plugins/jquery-datatable/DataTables-1.10.16/js/dataTables.bootstrap.min.js') ?>" type="text/javascript"></script>
