<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar" >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1> Funnel
                <?php //echo $this->translate('Imalat Control Panel') ?>
                <small></small>
            </h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content" id="test">
            
            <!-- Hedefler karsılaştırma blok-->
            <!--<div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div id='listboxHedefler' class="box box-primary">
                <div class="box-header ui-sortable-handle" style="cursor: move;">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title">Hedefler</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                 </div>
                </div><!-- /.box-header -->
                <!--<div class="box-body">
                  <ul class="todo-list ui-sortable">
                    <li>
                      <!-- drag handle -->
                      <!--<span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <!-- checkbox -->
                      <!--<input type="checkbox" value="" name="">
                      <!-- todo text -->
                      <!--<span class="text">Kazanılması Gereken Toplam Proje Sayısı</span>
                      <!-- Emphasis label -->
                      
                      <!-- General tools such as edit or delete-->
                      <!--<div class="tools" style="display:block;" >
                          <small class="label label-danger" id="hedef_1" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      <!--</div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <span class="text">Teklif Edilmesi Gereken Toplam Teklif Sayısı</span>
                      
                      <div class="tools" style="display:block;">
                          <small class="label label-info" id="hedef_2" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      <!--</div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <span class="text">Yaratılması Gereken Toplam Proje Sayısı</span>
                      
                      <div class="tools" style="display:block;">
                          <small class="label label-warning" id="hedef_3" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      <!--</div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <span class="text">Tamamlanması Gereken Toplam Aktivite Sayısı</span>
                      
                      <div class="tools" style="display:block;">
                          <small class="label label-success" id="hedef_4" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      <!--</div>
                    </li>
                   
                    
                  </ul>
                </div><!-- /.box-body -->
                <!--<div class="box-footer clearfix no-border">
                    <div class="row">
                    <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                      <input type="text" class="knob" data-readonly="true" value="20" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                      <div class="knob-label">Mail-Orders</div>
                    </div><!-- ./col -->
                    <!--<div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                      <input type="text" class="knob" data-readonly="true" value="50" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                      <div class="knob-label">Online</div>
                    </div><!-- ./col -->
                    <!--<div class="col-xs-4 text-center">
                      <input type="text" class="knob" data-readonly="true" value="30" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                      <div class="knob-label">In-Store</div>
                    </div><!-- ./col -->
                  <!--</div><!-- /.row -->
                  <!--<button class="btn btn-default pull-right"><i class="fa fa-plus"></i> Add item</button>-->
                <!--</div>
              </div>
                </div><!-- /.col -->
                
                
            <!--</div>-->
            <!-- Hedefler karsılaştırma blok son-->
            
            <!-- Eylemler karsılaştırma blok-->
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div id='listboxEylemler' class="box box-primary">
                <div class="box-header ui-sortable-handle" style="cursor: move;">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title"><span lang="en">Actions</span></h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <ul class="todo-list ui-sortable">
                    <li id="eylemler_li">
                      <!-- drag handle -->
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <!-- checkbox -->
                      <input type="checkbox" value="" name="">
                      <!-- todo text - RVP Toplam Kamyon Satış Sayısı -->
                      <span class="text" lang="en">RVP Total Truck Sales</span> 
                      <!-- Emphasis label -->
                      
                      <!-- General tools such as edit or delete-->
                      <div class="tools" style="display:block;" > 
                          <small class="label label-danger" id="eylem_1" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      </div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <!-- KAMU Satış Hedef Sayısı -->    
                      <span class="text" lang="en">PUBLIC Sales Target Number</span>
                      
                      <div class="tools" style="display:block;">
                          <small class="label label-info" id="eylem_2" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      </div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <!-- IKA Satış Hedef Sayısı -->    
                      <span class="text" lang="en">IKA Sales Target Number</span>
                      
                      <div class="tools" style="display:block;">
                          <small class="label label-warning" id="eylem_3" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      </div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <!--Bir Önceki Yılın Bayi Stok Sayısı -->    
                      <span class="text" lang="en">Number of Reseller Inventory for Previous Year</span>
                      
                      <div class="tools" style="display:block;">
                          <small class="label label-success" id="eylem_4" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      </div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <!-- Yıl Sonu Bayi Stok Hedef Sayısı -->    
                      <span class="text" lang="en">Year-End Dealer Stock Goal Count</span>
                      
                      <div class="tools" style="display:block;">
                          <small class="label label-primary" id="eylem_5" style="font-size: 15px;"></i></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      </div>
                    </li>
                    <li>
                      <span class="handle ui-sortable-handle">
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                      <input type="checkbox" value="" name="">
                      <!-- Yıllık RETAIL Satış Hedef -->    
                      <span class="text" lang="en">Annual RETAIL Sales Target</span>
                      
                      <div class="tools" style="display:block;">
                          <small class="label label-default" id="eylem_6" style="font-size: 15px;"></small>
                        <!--<i class="fa fa-edit"></i>
                        <i class="fa fa-trash-o"></i>-->
                      </div>
                    </li>
                  </ul>
                </div><!-- /.box-body -->
                <div class="box-footer clearfix no-border">
                    <!--<div class="row">
                    <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                      <input type="text" class="knob" data-readonly="true" value="20" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                      <div class="knob-label">Mail-Orders</div>
                    </div><!-- ./col -->
                    <!--<div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                      <input type="text" class="knob" data-readonly="true" value="50" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                      <div class="knob-label">Online</div>
                    </div><!-- ./col -->
                    <!--<div class="col-xs-4 text-center">
                      <input type="text" class="knob" data-readonly="true" value="30" data-width="60" data-height="60" data-fgColor="#39CCCC"/>
                      <div class="knob-label">In-Store</div>
                    </div><!-- ./col -->
                  <!--</div><!-- /.row -->
                  <!--<button class="btn btn-default pull-right"><i class="fa fa-plus"></i> Add item</button>-->
                </div>
              </div>
                </div><!-- /.col -->
                
                
            </div>
            <!-- Eylemler karsılaştırma blok son-->
            
            <!-- Funnel graph blok-->
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div id='listboxEylemler' class="box box-primary">
                <div class="box-header ui-sortable-handle" style="cursor: move;">
                  <i class="ion ion-clipboard"></i>
                  <h3 class="box-title"><span lang="en">Sales Funnel</span></h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
                </div><!-- /.box-header -->
                <div class="box-body">
                    <div id="container" style=" min-width: 280px; height: 400px; margin: 0 auto"></div>
                </div><!-- /.box-body -->
                <div class="box-footer clearfix no-border">
                </div>
              </div>
                </div><!-- /.col -->
                
                
            </div>
            <!-- Funnel graph  blok son-->
            
            
            
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php /*echo $this->partial('partials/admincontrolasidepartial.phtml');*/ ?>
    <!-- Control Sidebar son--> 
</div><!-- ./wrapper -->

    <!-- sayfa içine yazılan js'ler ekleniyor-->
    <script src="<?php echo $this->basePath('jsinline/admin_fun.js') ?>" type="text/javascript"></script>