<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>
<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar " >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            
            <!-- Call uts  -->
            <!--<div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-text-width"></i>
                            <h3 class="box-title">
                                Dashboard
                                <small>Kontrol panel</small>
                            </h3>
                        </div><!-- /.box-header -->
                        <!--<div class="box-body">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div><!-- /.box-body -->
                    <!--</div><!-- /.box -->
                <!--</div><!-- ./col -->
            <!--</div><!-- /.row -->
            <!-- Call Outs end  -->
            
            
            <h1 lang="en">Management Dashboard</h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content">
            
            <!--servisler blok-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box ">
                    <div class="box-header with-border">
                      <h3 class="box-title" lang="en">Services</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool"  id="servisDashboardHesapla"><i class="fa fa-refresh"></i></button>
                        <button id="test-collapse" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      
                        
                        <form id='actionsForm' method="get" class="form-horizontal">   
                    
                                            
                                            <div class="">
                                                <div id="loading-image-roles" class="input-group">    
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-copyright"></i>
                                                    </div>
                                                    <div id="dropdownRoles" ></div>
                                                </div>
                                                
                                            </div>
                                            <div class="">
                                                <div id="loading-image-roles" class="input-group">    
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-hand-o-right"></i>
                                                    </div>
                                                    <div style="margin-bottom: -10px;width:96%" class="tag-container">
                                                        <ul id="test-cabin" class="tag-box"></ul>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                        <!--<div class="form-group">
                                            <div class="col-sm-10 col-sm-offset-2">
                                                <button id="insertMachineCategory" class="btn btn-primary" type="submit" onclick="return insertActionsWrapper(event);"><i class="fa fa-save"></i>  Action Kaydet </button>
                                                <button id="resetForm" class="btn btn-flat" type="reset" onclick="resetActionsForm();"><i class="fa fa-remove"></i> Reset </button>
                                            </div>
                                        </div>-->
                   
                      
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--servisler blok son-->

            <!-- aftersales dashboard data ana blok -->
            <div class="row">
                <div class="col-lg-4 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_yedek_parca_hedef_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner"></div>
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <!--<i class="fa fa-refresh fa-spin" ></i>-->
                                </div>
                            </h3>
                            <p lang="en">Service Spare Part Target</p>
                        </div>
                        <div class="inner"></div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="cursor: pointer;" id="yedek_parca_hedef" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- aftersales dashboard data ana blok son -->
            
            <!--hedef  hidden block  -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hedef" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hedef_title" lang="en">TARGET</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <!-- stok baş.-->
                        <div class="col-lg-12 col-xs-12">
                        <!-- small box -->
                            <div id="servis_hedef_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <p lang="en">Service Spare Part Target</p>
                                </div>
                            </div>
                        
                          <table id="grid_hedef" class="table table-striped table-bordered" class="display" style="width:100%">
                            <thead>
                                <tr>
                                    <th><span lang="en">No</span></th>
                                    <th><span lang="en">Service Name</span></th>
                                    <th><span lang="en">Type</span></th>
                                    <th><span lang="en">Jan-May 2017</span></th>
                                    <th><span lang="en">Jan-May 2018</span></th>
                                    <th><span lang="en">Comparison 2017-2018</span></th>
                                    <th><span lang="en">Total 2017</span></th>
                                    <th><span lang="en">3 Year Average</span></th>
                                    <th><span lang="en">Monthly Realization Amount</span></th>                              
                                    <th><span lang="en">Amount required for 7% per month</span></th>
                                    <th><span lang="en">Amount required for 8% per month</span></th>
                                    <th><span lang="en">Amount required for 9% per month</span></th>
                                    <th><span lang="en">Amount Remaining for 7% per annum</span></th>
                                    <th><span lang="en">Amount Remaining for 8% per annum</span></th>
                                    <th><span lang="en">Amount Remaining for 9% per annum</span></th>
                                    <!--<th>Partnercode</th> -->

                                </tr>
                            </thead>
                            
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>Type</th>
                                    <th>Ocak-Mayıs 2017</th>
                                    <th>Ocak-Mayıs 2018</th>
                                    <th>Karşılaştırma 2017-2018</th>
                                    <th>Toplam 2017</th>
                                    <th>3 Yıllık Ortalama</th>
                                    <th>Aylık Gerçekleşme Miktarı</th>                              
                                    <th>Aylık %7 için Gereken Miktar</th>
                                    <th>Aylık %8 için Gereken Miktar</th>
                                    <th>Aylık %9 için Gereken Miktar</th>
                                    <th>Yıllık %7 için Kalan Miktar</th>
                                    <th>Yıllık %8 için Kalan Miktar</th>
                                    <th>Yıllık %9 için Kalan Miktar</th>
                                    <!--<th>Partnercode</th>-->
                                </tr>
                            </tfoot>
                        </table>
                          
                          
                        </div><!-- /.col -->
                        </div><!-- /.col -->
                        <!-- hedef son.-->

                      </div><!-- /.row -->
                      <div class="row">
                        <div class="col-md-12">
                          
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    <div class="box-footer" style="display: block;">                     
                    </div><!-- /.box-footer -->                      
                    </div><!-- ./box-body -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hedef hidden block son-->

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php /*echo $this->partial('partials/admincontrolasidepartial.phtml');*/ ?>
    <!-- Control Sidebar son-->   
    
</div><!-- ./wrapper -->
<!-- sayfa içine yazılan js'ler ekleniyor-->
<script src="<?php echo $this->basePath('jsinline/dealerowner_hedef.js') ?>" type="text/javascript"></script>

 <!-- easyui implementation -->
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/jquery.easyui.min.js') ?>"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/locale/easyui-lang-tr.js') ?>"></script>
<script src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/src/datagrid-filter.js') ?>"></script>

<!-- ddslick select plugin ekleniyor-->
<script src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.js') ?>" type="text/javascript"></script>

<!-- tagCabin Js-->
<script src="<?php echo $this->basePath('plugins/zeynel/tag-cabin/tag-cabin.js') ?>" type="text/javascript"></script>  

<!-- jquery-number plugin-->
<script src="<?php echo $this->basePath('plugins/jquery-number/jquery.number.min.js') ?>" type="text/javascript"></script>

<!-- jquery data-table -->
<script src="<?php echo $this->basePath('plugins/jquery-datatable/datatables.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('plugins/jquery-datatable/DataTables-1.10.16/js/dataTables.bootstrap.min.js') ?>" type="text/javascript"></script>
