<?php /* $this->layout('layout/error'); */ ?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->  
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->  
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->  

    <!-- Mirrored from htmlstream.com/preview/unify-v1.8/page_404_error2.html by HTTrack Website Copier/3.x [XR&CO'2010], Wed, 09 Dec 2015 11:53:31 GMT -->
    <head>
        <!--<title><?php echo $this->translate('404 Error Page') ?> | <?php echo $this->translate('Virtual Enterprise') ?> - <?php echo $this->translate('Authentication') ?></title>-->

        <!-- Meta -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Favicon -->
        <link rel="shortcut icon" href="favicon.ico">
        <!-- CSS Page Style -->    
        <link rel="stylesheet" href="<?php echo $this->basePath('errorpages/404/css/404.css') ?>">

        
    </head> 

    <body>
        <?php echo $this->content; ?>
    </body>
</html>
