<?php // partial.phtml ?>
<!-- Control Sidebar -->      
    <aside class="control-sidebar control-sidebar-dark">                
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
            <li><a href="#control-sidebar-theme-demo-options-tab" data-toggle="tab"><i class="fa fa-wrench"></i></a></li>
            <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <!-- Home tab content -->
            <div class="tab-pane" id="control-sidebar-home-tab">
                <div>
                    <h3 class="control-sidebar-heading"><?php echo $this->translate('Recent Activities') ?></h3>
                    <ul class='control-sidebar-menu'>
                        <li>
                            <a href='javascript::;'>
                                <i class="menu-icon-zeyn fa fa-file-code-o bg-green"></i>
                                <div class="menu-info">
                                    <h4 class="control-sidebar-subheading"><?php echo $this->translate('Logged in') ?></h4>
                                    <p><!--Will be 23 on April 24th--></p>
                                </div>
                            </a>
                        </li>
                        <!--<li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-user bg-yellow"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>
                              <p>New phone +1(800)555-1234</p>
                            </div>
                          </a>
                        </li>
                        <li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>
                              <p>nora@example.com</p>
                            </div>
                          </a>
                        </li>
                        <li>
                          <a href='javascript::;'>
                            <i class="menu-icon-zeyn fa fa-envelope-o bg-light-blue"></i>
                            <div class="menu-info">
                              <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>
                              <p>Execution time 5 seconds</p>
                            </div>
                          </a>
                        </li>-->
                    </ul><!-- /.control-sidebar-menu -->

                    <h3 class="control-sidebar-heading"><?php echo $this->translate('Tasks Progress') ?></h3> 
                    <ul class='control-sidebar-menu'>
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    Ziyaret Edilen Firmalar
                                    <span class="label label-danger pull-right">3%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-danger" style="width: 3%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    Tamamlanan Temiz Üretim Raporları
                                    <span class="label label-success pull-right">0%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-success" style="width: 0%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <li>
                            <a href='javascript::;'>               
                                <h4 class="control-sidebar-subheading">
                                    Tamamlanan Enerji Verimliliği Raporları
                                    <span class="label label-waring pull-right">0%</span>
                                </h4>
                                <div class="progress progress-xxs">
                                    <div class="progress-bar progress-bar-warning" style="width: 0%"></div>
                                </div>                                    
                            </a>
                        </li> 
                        <!--<li>
                          <a href='javascript::;'>               
                            <h4 class="control-sidebar-subheading">
                              Back End Framework
                              <span class="label label-primary pull-right">68%</span>
                            </h4>
                            <div class="progress progress-xxs">
                              <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
                            </div>                                    
                          </a>
                        </li>-->             
                    </ul><!-- /.control-sidebar-menu -->         
                </div>
            </div><!-- /.tab-pane -->
            <!-- Stats tab content -->

            <div class="tab-pane active" id="control-sidebar-theme-demo-options-tab"><?php echo $this->translate('Stat Tab Content Options') ?>
                <!--/ sonradan js'den cekılıp html'e yerleştirilen tab bölümü-->

                <h4 class="control-sidebar-heading"><?php echo $this->translate('Layout Options') ?></h4>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <input type="checkbox" data-layout="fixed" class="pull-right"><?php echo $this->translate('Fixed layout') ?></label>
                    <p><?php echo $this->translate("Activate the fixed layout. You can't use fixed and boxed layouts together") ?></p>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <input type="checkbox" data-layout="layout-boxed" class="pull-right"><?php echo $this->translate('Boxed Layout') ?></label>
                    <p><?php echo $this->translate('Activate the boxed layout') ?></p>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <input type="checkbox" data-layout="sidebar-collapse" class="pull-right"><?php echo $this->translate('Toggle Sidebar') ?></label>
                    <p><?php echo $this->translate("Toggle the left sidebar's state (open or collapse)") ?></p>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <input type="checkbox" data-enable="expandOnHover" class="pull-right"><?php echo $this->translate('Sidebar Expand on Hover') ?></label>
                    <p><?php echo $this->translate("Let the sidebar mini expand on hover") ?></p>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <input type="checkbox" data-controlsidebar="control-sidebar-open" class="pull-right"><?php echo $this->translate('Toggle Right Sidebar Slide') ?></label>
                    <p><?php echo $this->translate("Toggle between slide over content and push content effects") ?></p>
                </div>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        <input type="checkbox" data-sidebarskin="toggle" class="pull-right"><?php echo $this->translate("Toggle Right Sidebar Skin") ?></label>
                    <p><?php echo $this->translate("Toggle between dark and light skins for the right sidebar") ?></p>
                </div>

                <h4 class="control-sidebar-heading"><?php echo $this->translate("Skins") ?></h4>

                <ul class="list-unstyled clearfix">
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-blue" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div><span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9;">

                                </span>
                                <span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin"><?php echo $this->translate("Blue") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-black" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix">
                                <span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe;"></span>
                                <span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #222;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin"><?php echo $this->translate("Black") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-purple" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
                                <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin"><?php echo $this->translate("Purple") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-green" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span>
                                <span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin"><?php echo $this->translate("Green") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-red" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span>
                                <span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin"><?php echo $this->translate("Red") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-yellow" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span>
                                <span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #222d32;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin"><?php echo $this->translate("Yellow") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-blue-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px; background: #367fa9;"></span>
                                <span class="bg-light-blue" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Blue Light") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-black-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div style="box-shadow: 0 0 2px rgba(0,0,0,0.1)" class="clearfix">
                                <span style="display:block; width: 20%; float: left; height: 7px; background: #fefefe;"></span>
                                <span style="display:block; width: 80%; float: left; height: 7px; background: #fefefe;"></span>
                            </div><div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Black Light") ?>/p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-purple-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-purple-active"></span>
                                <span class="bg-purple" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Purple Light") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-green-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-green-active"></span>
                                <span class="bg-green" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div><div><span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Green Light") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-red-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-red-active"></span>
                                <span class="bg-red" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin" style="font-size: 12px"><?php echo $this->translate("Red Light") ?></p>
                    </li>
                    <li style="float:left; width: 33.33333%; padding: 5px;">
                        <a href="javascript:void(0);" data-skin="skin-yellow-light" style="display: block; box-shadow: 0 0 3px rgba(0,0,0,0.4)" class="clearfix full-opacity-hover">
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 7px;" class="bg-yellow-active"></span>
                                <span class="bg-yellow" style="display:block; width: 80%; float: left; height: 7px;"></span>
                            </div>
                            <div>
                                <span style="display:block; width: 20%; float: left; height: 20px; background: #f9fafc;"></span>
                                <span style="display:block; width: 80%; float: left; height: 20px; background: #f4f5f7;"></span>
                            </div>
                        </a>
                        <p class="text-center no-margin" style="font-size: 12px;"><?php echo $this->translate("Yellow Light") ?></p>
                    </li>
                </ul>

            </div><!--/ sonradan js'den cekılıp html'e yerleştirilen tab bölümü-->


            <!--<div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
            <!-- Settings tab content -->
            <div class="tab-pane" id="control-sidebar-settings-tab">            
                <form method="post">
                    <h3 class="control-sidebar-heading"><?php echo $this->translate('General Settings') ?></h3>

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Report panel usage') ?>
                            <input type="checkbox" class="pull-right" checked />
                        </label>
                        <p>
                            <?php echo $this->translate('Some information about this general settings option') ?>
                        </p>
                    </div><!-- /.form-group -->

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Allow mail redirect') ?>
                            <input type="checkbox" class="pull-right" checked />
                        </label>
                        <p>
                            <?php echo $this->translate('Other sets of options are available') ?>
                        </p>
                    </div><!-- /.form-group -->

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Other sets of options are available') ?>
                            <input type="checkbox" class="pull-right" checked />
                        </label>
                        <p>
                            <?php echo $this->translate('Expose author name in posts') ?>
                        </p>
                    </div><!-- /.form-group -->

                    <h3 class="control-sidebar-heading"><?php echo $this->translate('Chat Settings') ?></h3>

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Show me as online') ?>
                            <input type="checkbox" class="pull-right" checked />
                        </label>                
                    </div><!-- /.form-group -->

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Turn off notifications') ?>
                            <input type="checkbox" class="pull-right" />
                        </label>                
                    </div><!-- /.form-group -->

                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            <?php echo $this->translate('Delete chat history') ?>
                            <a href="javascript::;" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
                        </label>                
                    </div><!-- /.form-group -->
                </form>
            </div><!-- /.tab-pane -->
        </div>
    </aside><!-- /.control-sidebar -->
    <!-- Add the sidebar's background. This div must be placed
         immediately after the control sidebar -->
    <div class='control-sidebar-bg'></div>