<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar" >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1> <span lang="en">Dealer Invoices</span>  <!-- Bayi Faturaları-->
                <?php //echo $this->translate('Imalat Control Panel') ?>
                <small></small>
            </h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content" id="test">
            
            <!-- aftersales dashboard data karsılaştırma blok-->
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="info-box bg-man-yellow">
                        <span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>
                        <div class="info-box-content" id="toplam_ciro_1_container">
                            <h3 style="margin-top: 12px;">
                                <div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                          <span class="info-box-text"></span>
                          <span class="info-box-number"></span>
                          <div class="progress" id="toplam_musteri_container_progress_bar">
                            <div class="progress-bar" style="width: 100%"></div>
                          </div>
                          <span class="progress-description" lang="en">
                            Bir önceki güne göre oran
                          </span>
                        </div><!-- /.info-box-content -->
                    </div>
                </div><!-- /.col -->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    
                    <div class="info-box bg-man-blue">
                <span class="info-box-icon"><i class="ion-ios-chatbubble-outline"></i></span>
                <div class="info-box-content" id="toplam_ciro_2_container">
                    <h3 style="margin-top: 12px;">
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                    </h3>
                  <span class="info-box-text"></span>
                  <span class="info-box-number"></span>
                  <div class="progress" id="toplam_ciro_container_progress_bar">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description" lang="en">
                    Bir önceki güne göre oran
                  </span>
                </div><!-- /.info-box-content -->
              </div>
                     
                    
                </div><!-- /.col -->
                
            </div>
            <!-- aftersales dashboard data karsılaştırma blok son-->
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php /*echo $this->partial('partials/admincontrolasidepartial.phtml');*/ ?>
    <!-- Control Sidebar son--> 
</div><!-- ./wrapper -->

    <!-- sayfa içine yazılan js'ler ekleniyor-->
    <script src="<?php echo $this->basePath('jsinline/managerdirector_dealerinv.js') ?>" type="text/javascript"></script>