<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="ln" type="hidden"  value="tr"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>


    <div class="wrapper">

        <!-- admin header -->
        <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
        <!-- admin header son-->

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar" >
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>

                <!-- search form -->
                <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
                <!-- /.search form -->

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    <?php echo $this->translate('Imalat Control Panel') ?>
                    Action Rol / Yetki Atama İşlemleri
                    <small></small>
                </h1>
                <!-- admin breadcrumb panel -->
                <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
                <!-- admin breadcrumb panel son-->
            </section>
            <!-- Main content -->
            <section class="content">
                <!-- Small boxes (Stat box) -->
                <!--first collapsible panel row -->
                <div class="row">
                    
                    
                    
                    <!--first collapsible panel width, single column-->
                    <div class="col-lg-12">
                        <!--arrange first panel color to blue by assigning primary class-->
                        <div id="loading-image-crud" class="box box-primary"> 
                            <!--First panel Header-->
                            <div class="box-header with-border">                                                    
                                <h3 class="box-title"> Action / Yetki İşlemleri </h3>
                                
                                <!--Panel 1 collapse button-->
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                </div><!--/. button div-->
                            </div><!--/. panel 1 header div-->
                            <!--Panel 1 contents-->
                            <div id='tab_image_loader' class="box box-body" style="border-top:0px;">
                                
                                
                            <div class="alert alert-info alert-dismissable">
                                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                <h4><i class="icon fa fa-info"></i> Sistemde kullanılan tüm action resource (kaynak)'ların  yetki ataması yapılabilir!</h4>
                                Öncelikle Action resource (kaynak) ağaç yapısından kaynak seçip rol ağacını doldurmalısınız, rol ağacından rol seçerek adımlara devam ediniz.
                            </div>    
                                
                                
            <!-- Custom Tabs -->
              <div class="nav-tabs-custom" >
                <ul id="mach_prop_tab_container" class="nav nav-tabs">
                  <li class="active" ><a href="#tab_mach_prop" id="tab_mach_prop_clicker" name="tab_mach_prop_clicker" data-toggle="tab">İşlem yapmak için Action resource (kaynak) ve rol seçmelisiniz</a></li>
                  <!--<li><a href="#tab_mach_prop_update" id="tab_mach_prop_update_clicker" name="tab_mach_prop_update_clicker" data-toggle="tab" >Makina Özelliği Güncelle</a></li>
                  <li class="pull-right"><a href="#" class="text-muted"><i class="fa fa-gear"></i></a></li>-->
                </ul>
                <div class="tab-content">
                  <div class="tab-pane active" id="tab_mach_prop">  
                    
                     <form id='unitForm' method="get" class="form-horizontal">     
                    
                    <div id="rolePrivilegeBlock" class="box box-primary" style="padding-top: 20px;">                                     
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Action Resource (Kaynak)</label>
                            <div class="col-sm-10 " >
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-code-fork"></i>
                                    </div>
                                    <div class="inner test-tree" style='overflow:auto;'>    
                                        <div id="loading-image-resource" style="height: 200px;" class='scrollbar-inner'>
                                        <ul id="tt_tree_menu2" class="easyui-tree" ></ul> 
                                        </div>
                                    </div>                                                       
                                </div>
                            </div>
                        </div>
                        <div  class="form-group box" style="border-top : 0px; box-shadow: none;">
                            <label class="col-sm-2 control-label">Atanmış Yetkiler</label>
                            <div class="col-sm-10">
                                <div class="input-group" id="mach-prop-box">    
                                    <div class="input-group-addon" >
                                        <i class="fa fa-hand-o-right"></i>
                                    </div>
                                    <div style="margin-bottom: -10px;" class="tag-container">
                                        <ul id="test-cabin" class="tag-box"></ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div  class="form-group box" style="border-top : 0px; box-shadow: none;">
                            <label class="col-sm-2 control-label">Atanmamış Yetkiler</label>
                            <div class="col-sm-10">
                                <div class="input-group" id="mach-prop-box-not">    
                                    <div class="input-group-addon">
                                        <i class="fa fa-hand-o-right"></i>
                                    </div>
                                    <div style="margin-bottom: -10px;" class="tag-container-not">
                                        <ul id="test-cabin-not" class="tag-box"></ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                        
                    </div> 
                </form>  
    
                  </div><!-- /.tab-pane -->
                  <!--<div class="tab-pane box" id="tab_mach_prop_update" >
 
                   
                    The European languages are members of the same family. Their separate existence is a myth.
                    For science, music, sport, etc, Europe uses the same vocabulary. The languages only differ
                    in their grammar, their pronunciation and their most common words. Everyone realizes why a
                    new common language would be desirable: one could refuse to pay expensive translators. To
                    achieve this, it would be necessary to have uniform grammar, pronunciation and more common
                    words. If several languages coalesce, the grammar of the resulting language is more simple
                    and regular than that of the individual languages.   
                   
                  </div>--><!-- /.tab-pane -->
                  
                </div><!-- /.tab-content -->
              </div><!-- nav-tabs-custom -->
                                
                                
                                
                                
                            </div><!-- /.box-body -->
                        </div><!--/. primary box div-->
                    </div><!--/. first panel single column div -->
                </div><!-- / first panel row-->

                

            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <!-- footer --> 
        <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
        <!-- footerson--> 

        <!-- Control Sidebar --> 
        <?php echo $this->partial('partials/admincontrolasidepartial.phtml'); ?>
        <!-- Control Sidebar son--> 
    </div><!-- ./wrapper -->
    
    <!-- sayfa içine yazılan js'ler ekleniyor-->
    <script src="<?php echo $this->basePath('jsinline/admin_actionprivilege.js') ?>" type="text/javascript"></script>
    
    <!-- easyui implementation -->
    <script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/jquery.easyui.min.js') ?>"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/locale/easyui-lang-tr.js') ?>"></script>
    <script src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/src/datagrid-filter.js') ?>"></script>
    
    <!-- Form validation js -->
    <script src="<?php  echo $this->basePath('plugins/validationEngine/jquery.validationEngine-tr.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('plugins/validationEngine/jquery.validationEngine.js') ?>" type="text/javascript"></script>
    
    <!-- ddslick select plugin ekleniyor-->
    <script src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.js') ?>" type="text/javascript"></script>
        
    <!-- tagCabin Js-->
    <script src="<?php echo $this->basePath('plugins/zeynel/tag-cabin/tag-cabin.js') ?>" type="text/javascript"></script>               

