<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="ln" type="hidden"  value="tr"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

    <div class="wrapper">

        <!-- admin header -->
        <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
        <!-- admin header son-->

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar" >
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>

                <!-- search form -->
                <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
                <!-- /.search form -->

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    <?php echo $this->translate('Imalat Control Panel') ?>
                    Action / Yetki / Servis İşlemleri
                    <small></small>
                </h1>
                <!-- admin breadcrumb panel -->
                <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
                <!-- admin breadcrumb panel son-->
            </section>
            <!-- Main content -->
            <section class="content">
                <!-- Small boxes (Stat box) -->
                <!--first collapsible panel row -->
                <div class="row">
                    
                    <!--Makina giriş bölümü -->
                    <div class="col-lg-12">
                        <!--arrange first panel color to blue by assigning primary class-->
                        <div id="loading-image-crud" class="box box-primary"> 
                            <!--First panel Header-->
                            <div class="box-header with-border">                                                    
                                <h3 class="box-title"> Rest Servis API / Action Tanımlama  İşlemleri </h3>
                                
                                <!--Panel 1 collapse button-->
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                </div><!--/. button div-->
                            </div><!--/. panel 1 header div-->
                            <!--Panel 1 contents-->
                            <div id='tab_image_loader' class="box box-body" style="border-top:0px;">
                                <div class="alert alert-info alert-dismissable">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                    <h4><i class="icon fa fa-info"></i> Sistemde Action ve Rol bazlı  Yetki / Rest Servis atamaları yapılabilir...</h4>
                                </div>  
                                <!--Makina ekleme formu -->
                                <form id='aclServiceForm' method="get" class="form-horizontal">     
                                    <div id="machineInsertBlock" class="box box-primary" style="padding-top: 20px;">                                       
                                        <div class="form-group" >
                                            <label class="col-sm-2 control-label">Action Resource  ve Bağlı Roller</label>
                                            <div class="col-sm-10 " >
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-code-fork"></i>
                                                    </div>
                                                    <div class="inner test-tree" style='overflow:auto;'>    
                                                        <div id="loading-image" class='scrollbar-inner' style="height: 250px;">
                                                        <ul id="tt_tree_menu2" class="easyui-tree" ></ul> 
                                                        </div>
                                                    </div>                                                       
                                                </div>
                                            </div>
                                        </div>
                                        <div  class="form-group" >
                                            <label class="col-sm-2 control-label">Yetkiler </label>
                                            <div class="col-sm-10">
                                                <div class="input-group">    
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-hand-o-right"></i>
                                                    </div>
                                                    <!--<input data-prompt-position="topLeft:70" class="form-control validate[required]" type="text" name="name_tr" id="name_tr" />-->
                                                    <table  id="tt_grid_dynamic_privileges" title="Yetkiler " ></table> 
                                                </div>
                                            </div>
                                        </div>
                                    </div> 
                                </form>  
                            </div><!-- /.box-body -->
                        </div><!--/. primary box div-->
                    </div><!--/. first panel single column div -->
                    
                    <!--Makina listeleme bölümü -->
                    <!--<div class="col-lg-12">
                        <div id="loading-image-grid-container" class="box box-warning"> 
                            <div class="box-header with-border">                                                    
                                <h3 class="box-title"> ACL Rest Servis Listesi</h3>
                                
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                </div>
                            </div>
                            <div class="box-body">    
                                <div class="alert alert-warning alert-dismissable">
                                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                    <h4><i class="icon fa fa-info"></i> ACL Servisler / Yetkiler Listesi </h4>
                                    ACL için yetkilerle ilişkilendirilmiş servisleri  filtreleyebilir, güncelleme, silme veya aktif / pasif işlemleri gerçekleştirebilirsiniz...
                                </div>
                                <div id="machinesGridBlock" class="box-warning" style="padding-top: 20px;">
                                    <table  id="tt_grid_dynamic" title="ACL Roller " ></table>  
                                </div> 
                                
                            </div>
                        </div>
                    </div> --> 
                </div><!-- / first panel row-->
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <!-- footer --> 
        <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
        <!-- footerson--> 

        <!-- Control Sidebar --> 
        <?php echo $this->partial('partials/admincontrolasidepartial.phtml'); ?>
        <!-- Control Sidebar son--> 
    </div><!-- ./wrapper -->
    
    <!-- sayfa içine yazılan js'ler ekleniyor-->
    <script src="<?php echo $this->basePath('jsinline/admin_actionprivilegeservice.js') ?>" type="text/javascript"></script>
        
    <!-- easyui implementation -->
    <script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/jquery.easyui.min.js') ?>"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/locale/easyui-lang-tr.js') ?>"></script>
    <script src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/src/datagrid-filter.js') ?>"></script>
    
    <!-- Form validation js -->
    <script src="<?php  echo $this->basePath('plugins/validationEngine/jquery.validationEngine-tr.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('plugins/validationEngine/jquery.validationEngine.js') ?>" type="text/javascript"></script>
    
    <!-- ddslick select plugin ekleniyor-->
    <script src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.js') ?>" type="text/javascript"></script>
        
    <!-- tagCabin Js-->
    <script src="<?php echo $this->basePath('plugins/zeynel/tag-cabin/tag-cabin.js') ?>" type="text/javascript"></script>               
