<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar " >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            
            <!-- Call uts  -->
            <!--<div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-text-width"></i>
                            <h3 class="box-title">
                                Dashboard
                                <small>Kontrol panel</small>
                            </h3>
                        </div><!-- /.box-header -->
                        <!--<div class="box-body">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div><!-- /.box-body -->
                    <!--</div><!-- /.box -->
                <!--</div><!-- ./col -->
            <!--</div><!-- /.row -->
            <!-- Call Outs end  -->
            
            
            <h1 lang="en">Management Dashboard</h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content">
            
            <!--servisler blok-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box ">
                    <div class="box-header with-border">
                      <h3 class="box-title" lang="en">Services</h3>
                      <div class="box-tools pull-right">
                        <button id="test-collapse" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      
                        
                        <form id='actionsForm' method="get" class="form-horizontal">   
                    
                                            
                                            <div class="">
                                                <div id="loading-image-roles" class="input-group">    
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-copyright"></i>
                                                    </div>
                                                    <div id="dropdownRoles" ></div>
                                                </div>
                                                
                                            </div>
                   
                      
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--servisler blok son-->
            
            

            
            <!-- aftersales dashboard data ikinci blok -->
            <div class="row">
                <div class="col-lg-4 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_1_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Yedek Parça</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="cursor: pointer;" id="detay_acik_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-4 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_2_container" class="small-box bg-man-ligth-grey bg-green">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Yağ</p>
                            
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_acilan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-4 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_3_container" class="small-box bg-man-ligth-grey bg-yellow">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Stok</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-briefcase"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->

            </div><!-- /.row -->
            <!-- aftersales dashboard data ikinci blok son -->
            
            <!--yedek parça (servis içinde onarıma kullanılan) block 2 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_yedek_parca_servis_ici" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_yedek_parca_servis_ici_title" lang="en">Servis içinde onarıma kullanılan</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block2_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block2_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <!-- yedek parca (servis içinde onarıma kullanılan)(uygun parça) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red">0</h3>
                                    <p lang="en">Uygun parça</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-briefcase"></i>
                                </div>
                                <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            <!-- uygun parça ücretli baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Ücretli</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ücretli son.-->
                            <!-- uygun parça garanti baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Garanti</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça garanti son.-->
                            <!-- uygun parça toplam baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Toplam</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça toplam son.-->
                            <!-- uygun parça OEM baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">OEM</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça OEM son.-->
                            <!-- uygun parça OES baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">OES</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça OES son.-->
                            <!-- uygun parça ESD baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">ESD</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ESD son.-->
                        </div><!-- /.col -->
                        <!-- yedek parca (servis içinde onarıma kullanılan)(uygun parça) son.-->
                        
                        <!-- yedek parca (servis içinde onarıma kullanılan)(Y.S parça) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red">0</h3>
                                    <p lang="en">Y.S Parça</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-briefcase"></i>
                                </div>
                                <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            <!-- uygun parça ücretli baş.-->
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Toplam rakam buaya koyulacak</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ücretli son.-->
                            
                            
                            <!-- Y.S parça Y.san baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Y.SAN</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça Y.san son.-->
                            <!-- Y.S parça Y.san.my baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Y.San.My</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça Y.san.my son.-->
                            <!-- Y.S parça toplam baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Toplam</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça toplam son.-->
                        </div><!-- /.col -->
                        <!-- yedek parca (servis ,ç,nde onarıma kullanılan)(Y.S parça) son.-->
                        
                      </div><!-- /.row -->
                      <div class="row">
                        <div class="col-md-12">
                          
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--yedek parça (servis içinde onarıma kullanılan) son-->
            
            <!--yedek parça (servis dışına/direk satılan) block 2 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_yedek_parca_servis_disi" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_yedek_parca_servis_disi_title" lang="en">Servis dışına/direk satılan</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block2_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block2_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <!-- yedek parca (servis içinde onarıma kullanılan)(uygun parça) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red">0</h3>
                                    <p lang="en">Uygun parça</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-briefcase"></i>
                                </div>
                                <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            <!-- uygun parça ücretli baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Ücretli</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ücretli son.-->
                            <!-- uygun parça garanti baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Garanti</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça garanti son.-->
                            <!-- uygun parça toplam baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Toplam</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça toplam son.-->
                            <!-- uygun parça OEM baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">OEM</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça OEM son.-->
                            <!-- uygun parça OES baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">OES</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça OES son.-->
                            <!-- uygun parça ESD baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">ESD</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ESD son.-->
                        </div><!-- /.col -->
                        <!-- yedek parca (servis içinde onarıma kullanılan)(uygun parça) son.-->
                        
                        <!-- yedek parca (servis içinde onarıma kullanılan)(Y.S parça) baş.-->
                        <div class="col-lg-6 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red">0</h3>
                                    <p lang="en">Y.S Parça</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-briefcase"></i>
                                </div>
                                <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                            </div>
                            <!-- uygun parça ücretli baş.-->
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue" style="margin-left:0px;margin-bottom: 0px;">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Toplam rakam buaya koyulacak</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- uygun parça ücretli son.-->
                            
                            
                            <!-- Y.S parça Y.san baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Y.SAN</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça Y.san son.-->
                            <!-- Y.S parça Y.san.my baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Y.San.My</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça Y.san.my son.-->
                            <!-- Y.S parça toplam baş.-->
                            <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12 " style="padding-left: 0px;padding-right: 0px;">
                                <div class="info-box bg-man-blue">
                                    <!--<span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>-->
                                    <div class="info-box-content" style="margin-left:0px;" id="toplam_ciro_1_container">

                                      <span class="info-box-text ">0</span>
                                      <span class="info-box-number" lang="tr">Toplam</span>
                                      <div class="progress" id="toplam_musteri_container_progress_bar">
                                        <div class="progress-bar" style="width: 0%;"></div>
                                      </div>
                                      <span class="progress-description">Bir önceki güne göre çok düşük</span>
                                    </div><!-- /.info-box-content -->
                                </div>
                            </div>
                            <!-- Y.S parça toplam son.-->
                        </div><!-- /.col -->
                        <!-- yedek parca (servis ,ç,nde onarıma kullanılan)(Y.S parça) son.-->
                        
                      </div><!-- /.row -->
                      <div class="row">
                        <div class="col-md-12">
                          
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--yedek parça (servis dışına/direk satılan) son-->
            
            
            
            <!-- aftersales dashboard data üçüncü blok -->
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_header_arac_giris_sayilari_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Vehicle Entries</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-alert"></i>
                        </div>
                        <a href="cursor: pointer;" id="detay_arac_girisleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_header_downtime_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Downtime</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-time"></i>
                        </div>
                        <a href="cursor: pointer;" id="detay_downtime" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- aftersales dashboard data üçüncü blok son -->
            
            <!--hidden data block 3 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden3" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden3_title" lang="en">Work order</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block3_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block3_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block3" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 3 son-->
            
            <!--hidden data block 3_1 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden3_1" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden3_1_title" lang="en">Downtime</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <!--<div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block3_1_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block3_1_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>-->
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block3_1" style="min-width: 200px;  margin: 0 auto"></div>
                          
                          <table id="grid_downtime" class="table table-striped table-bordered" class="display" style="width:100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>DownTime</th>
                                    <th>Yıl</th>
                                    <th>Ay</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>DownTime</th>
                                    <th>Yıl</th>
                                    <th>Ay</th>
                                </tr>
                            </tfoot>
                        </table>
                          
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 3_1 son-->
            
 
            
            <!-- Main row -->
            <div class="row">
            
                <section class="col-lg-6 connectedSortable">
                    
                    

                    <!-- quick email widget -->
                    <div class="box ">
                        <div class="box-header">
                            <i class="fa fa-envelope"></i>
                            <h3 class="box-title" lang="en">Email</h3>
                            <!-- tools box -->
                            <div class="pull-right box-tools">
                                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div><!-- /. tools -->
                        </div>
                        <div class="box-body">
                            <form action="#" method="post">
                                <div class="form-group">
                                    <input type="email" lang="en" class="form-control" name="Kime" placeholder="to who"/>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="Konu" lang="en" placeholder="subject"/>
                                </div>
                                <div>
                                    <textarea class="textarea" lang="en" placeholder="message" style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>
                            </form>
                        </div>
                        <div class="box-footer clearfix">
                            <button class="pull-right btn btn-default" id="sendEmail" lang="en">Send<i class="fa fa-arrow-circle-right"></i></button>
                        </div>
                    </div>


                </section><!-- /.Left col -->
                <!-- right col (We are only adding the ID to make the widgets sortable)-->
                <section class="col-lg-6 connectedSortable">


                    <!-- Map box -->
                    <div class="box box-solid bg-light-blue-gradient">
                        <div class="box-header">
                            <!-- tools box -->
                            <div class="pull-right box-tools">
                              <!--<button class="btn btn-primary btn-sm daterange pull-right" data-toggle="tooltip" title="Date range"><i class="fa fa-calendar"></i></button>-->
                                <button class="btn btn-primary btn-sm pull-right" data-widget='collapse' data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
                            </div><!-- /. tools -->

                            <i class="fa fa-map-marker"></i>
                            <h3 class="box-title">
                                <!--Üye Ülkeler-->
                            </h3>
                        </div>
                        <div class="box-body">
                            <div id="world-map" style="height: 250px; width: 100%;"></div>
                        </div><!-- /.box-body-->
                        <div class="box-footer no-border">
                            <div class="row">
                                <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                                    <div id="sparkline-1"></div>
                                    <div class="knob-label"><!--OSB Imalat verileri...--></div>
                                </div><!-- ./col -->
                                <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                                    <div id="sparkline-2"></div>
                                    <div class="knob-label"><!--OSB Imalat verileri...--></div>
                                </div><!-- ./col -->
                                <div class="col-xs-4 text-center">
                                    <div id="sparkline-3"></div>
                                    <div class="knob-label"><!--OSB Imalat verileri...--></div>
                                </div><!-- ./col -->
                            </div><!-- /.row -->
                        </div>
                    </div>
                    <!-- /.box -->

                </section><!-- right col -->
            </div><!-- /.row (main row) -->

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php echo $this->partial('partials/admincontrolasidepartial.phtml'); ?>
    <!-- Control Sidebar son-->   
    
</div><!-- ./wrapper -->
<!-- sayfa içine yazılan js'ler ekleniyor-->
<script src="<?php echo $this->basePath('jsinline/admin_faal.js') ?>" type="text/javascript"></script>

 <!-- easyui implementation -->
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/jquery.easyui.min.js') ?>"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/locale/easyui-lang-tr.js') ?>"></script>
<script src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/src/datagrid-filter.js') ?>"></script>

<!-- ddslick select plugin ekleniyor-->
<script src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.js') ?>" type="text/javascript"></script>

<!-- tagCabin Js-->
<script src="<?php echo $this->basePath('plugins/zeynel/tag-cabin/tag-cabin.js') ?>" type="text/javascript"></script>  

<!-- jquery-number plugin-->
<script src="<?php echo $this->basePath('plugins/jquery-number/jquery.number.min.js') ?>" type="text/javascript"></script>

<!-- jquery data-table -->
<script src="<?php echo $this->basePath('plugins/jquery-datatable/datatables.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('plugins/jquery-datatable/DataTables-1.10.16/js/dataTables.bootstrap.min.js') ?>" type="text/javascript"></script>
