<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar " >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            
            <!-- Call uts  -->
            <!--<div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-text-width"></i>
                            <h3 class="box-title">
                                Dashboard
                                <small>Kontrol panel</small>
                            </h3>
                        </div><!-- /.box-header -->
                        <!--<div class="box-body">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div><!-- /.box-body -->
                    <!--</div><!-- /.box -->
                <!--</div><!-- ./col -->
            <!--</div><!-- /.row -->
            <!-- Call Outs end  -->
            
            
            <h1 lang="en">Management Dashboard</h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content">
            
            <!--servisler blok-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box ">
                    <div class="box-header with-border">
                      <h3 class="box-title" lang="en">Services</h3>
                      <div class="box-tools pull-right">
                        <button id="test-collapse" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      
                        
                        <form id='actionsForm' method="get" class="form-horizontal">   
                    
                                            
                                            <div class="">
                                                <div id="loading-image-roles" class="input-group">    
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-copyright"></i>
                                                    </div>
                                                    <div id="dropdownRoles" ></div>
                                                </div>
                                                
                                            </div>
                   
                      
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--servisler blok son-->

            <!-- aftersales dashboard data ana blok -->
            <div class="row">
                <div class="col-lg-12 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_header_yedek_parca_hedef_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Servis Yedek Parça Hedef</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="cursor: pointer;" id="yedek_parca_hedef" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- aftersales dashboard data ana blok son -->
            
            <!--yedek parça hedef hidden block  -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_yedek_parca_hedef" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_yedek_parca_hedef_title" lang="en">Servis Yedek Parça Hedef</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                       
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <!-- yedek parca hedef baş.-->
                        <div class="col-lg-12 col-xs-12">
                        <!-- small box -->
                            <div id="servisici_uygun_parca_container" class="small-box bg-man-ligth-grey bg-yellow" style="margin-bottom: 0px">
                                <div class="inner">
                                    <!--<h3 class="man-header-red"><div class="overlay" >0
                                            <i class="fa fa-refresh fa-spin" ></i>
                                        </div>
                                    </h3>-->
                                    <h3 class="man-header-red">Servis Yedek Parça Hedef</h3>
                                    <p lang="en">İlk satır "Garanti Hariç", İkinci satır "MAN Genuine Oil", Üçüncü satır "Garanti", Dördüncü satır "Toplam" ifade etmektedir.  
                                    </p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-android-bus"></i>
                                </div>
                                <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">&nbsp;&nbsp;</a>
                            </div>
                           
                            </div>

                        </div><!-- /.col -->
                        <!-- yedek parca hedef son.-->
                        <table id="grid_hedef" class="table table-striped table-bordered" class="display" style="width:100%">
                            <thead>
                                <tr>
                                    <th>2017 YTD</th>
                                    <th>2018 YTD</th>
                                    <th>2017-2018 YTD Karş.</th>
                                    <th>2017 Toplam</th>
                                    <th>3 Yıllık Ort.</th>
                                    <th>Aylık Ort. Miktar</th>
                                    <th>%7 için Gereken Aylık Miktar</th>
                                    <th>%8 için Gereken Aylık Miktar</th>
                                    <th>%9 için Gereken Aylık Miktar</th>
                                    <th>%7 için Kalan Yıllık Miktar</th>
                                    <th>%8 için Kalan Yıllık Miktar</th>
                                    <th>%9 için Kalan Yıllık Miktar</th>
                                </tr>
                            </thead>

                            <tfoot>
                                <tr>
                                    <th>2017 YTD</th>
                                    <th>2018 YTD</th>
                                    <th>2017-2018 YTD Karş.</th>
                                    <th>2017 Toplam</th>
                                    <th>3 Yıllık Ort.</th>
                                    <th>Aylık Ort. Miktar</th>
                                    <th>%7 için Gereken Aylık Miktar</th>
                                    <th>%8 için Gereken Aylık Miktar</th>
                                    <th>%9 için Gereken Aylık Miktar</th>
                                    <th>%7 için Kalan Yıllık Miktar</th>
                                    <th>%8 için Kalan Yıllık Miktar</th>
                                    <th>%9 için Kalan Yıllık Miktar</th>
                                </tr>
                            </tfoot>
                        </table>
                        
                      </div><!-- /.row -->
                      <div class="row">
                        <div class="col-md-12">
                          
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">

                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--yedek parça hedef hidden blok son-->
            

            <!-- Main row -->
            <div class="row">
            
                <section class="col-lg-6 connectedSortable">

                </section><!-- /.Left col -->
                <!-- right col (We are only adding the ID to make the widgets sortable)-->
                <section class="col-lg-6 connectedSortable">

                </section><!-- right col -->
            </div><!-- /.row (main row) -->

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php echo $this->partial('partials/admincontrolasidepartial.phtml'); ?>
    <!-- Control Sidebar son-->   
    
</div><!-- ./wrapper -->
<!-- sayfa içine yazılan js'ler ekleniyor-->
<script src="<?php echo $this->basePath('jsinline/admin_hedef.js') ?>" type="text/javascript"></script>

 <!-- easyui implementation -->
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/jquery.easyui.min.js') ?>"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/locale/easyui-lang-tr.js') ?>"></script>
<script src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/src/datagrid-filter.js') ?>"></script>

<!-- ddslick select plugin ekleniyor-->
<script src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.js') ?>" type="text/javascript"></script>

<!-- tagCabin Js-->
<script src="<?php echo $this->basePath('plugins/zeynel/tag-cabin/tag-cabin.js') ?>" type="text/javascript"></script>  

<!-- jquery-number plugin-->
<script src="<?php echo $this->basePath('plugins/jquery-number/jquery.number.min.js') ?>" type="text/javascript"></script>

<!-- jquery data-table -->
<script src="<?php echo $this->basePath('plugins/jquery-datatable/datatables.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('plugins/jquery-datatable/DataTables-1.10.16/js/dataTables.bootstrap.min.js') ?>" type="text/javascript"></script>
