<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar " >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            
            <!-- Call uts  -->
            <!--<div class="row">
                <div class="col-md-12">
                    <div class="box box-solid">
                        <div class="box-header with-border">
                            <i class="fa fa-text-width"></i>
                            <h3 class="box-title">
                                Dashboard
                                <small>Kontrol panel</small>
                            </h3>
                        </div><!-- /.box-header -->
                        <!--<div class="box-body">
                            <blockquote>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
                                <small>Someone famous in <cite title="Source Title">Source Title</cite></small>
                            </blockquote>
                        </div><!-- /.box-body -->
                    <!--</div><!-- /.box -->
                <!--</div><!-- ./col -->
            <!--</div><!-- /.row -->
            <!-- Call Outs end  -->
            
            
            <h1 lang="en">Management Dashboard</h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content">
            
            <!--servisler blok-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box ">
                    <div class="box-header with-border">
                      <h3 class="box-title" lang="en">Services</h3>
                      <div class="box-tools pull-right">
                          <button class="btn btn-box-tool"  id="servisDashboardHesapla"><i class="fa fa-refresh"></i></button>
                        <button id="test-collapse" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      
                        
                        <form id='actionsForm' method="get" class="form-horizontal">   
                    
                                            
                                            <div class="">
                                                <div id="loading-image-roles" class="input-group">    
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-copyright"></i>
                                                    </div>
                                                    <div id="dropdownRoles" ></div>
                                                </div>
                                                
                                            </div>
                                        <!--<div class="form-group">
                                            <div class="col-sm-10 col-sm-offset-2">
                                                <button id="insertMachineCategory" class="btn btn-primary" type="submit" onclick="return insertActionsWrapper(event);"><i class="fa fa-save"></i>  Action Kaydet </button>
                                                <button id="resetForm" class="btn btn-flat" type="reset" onclick="resetActionsForm();"><i class="fa fa-remove"></i> Reset </button>
                                            </div>
                                        </div>-->
                   
                      
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--servisler blok son-->
            
            
            <!-- aftersales dashboard data ilk blok -->
            <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12 flip-container "  ontouchstart="this.classList.toggle('hover');">
                    <div class="info-box overlay front">
                  
                    <span class="info-box-icon  bg-man-red"><i class="ion ion-ios-information"></i></span>
                    <div class="info-box-content " id="toplam_fatura_1_container">
                        <h3 id="" >
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                      <span class="info-box-text info-box-text-fatura"></span>
                      <a id="detay_acilan_alis_faturalari" style="cursor: pointer;" class="small-box-footer">
                          <i class="fa fa-arrow-circle-right"></i>
                          <span class="info-box-number" style="display: inline;font-size: 15px;" lang="en">Purchase invoices</span> 
                      </a>
                      
                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon    bg-man-red"><i class="ion ion-ios-information"></i></span>
                <div class="info-box-content" id="toplam_fatura_2_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                    </h3>
                    <span class="info-box-text info-box-text-fatura"></span>
                    <a id="detay_acilan_isemri_faturalari" style="cursor: pointer;" class="small-box-footer">
                        <i class="fa fa-arrow-circle-right"></i>
                        <span class="info-box-number" style="display: inline;font-size: 15px;" lang="en">Business order invoices</span> 
                    </a>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon   bg-man-red"><i class="ion ion-ios-information"></i></span>
                <div class="info-box-content" id="toplam_fatura_3_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                  </h3>
                  <span class="info-box-text info-box-text-fatura"></span>
                  <a id="detay_acilan_satis_faturalari" style="cursor: pointer;" class="small-box-footer">
                        <i class="fa fa-arrow-circle-right"></i>
                        <span class="info-box-number" style="display: inline;font-size: 15px;" lang="en">Sales invoices</span> 
                    </a>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon  bg-man-red"><i class="ion ion-ios-information"></i></span>
                <div class="info-box-content" id="toplam_fatura_4_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                  </h3>
                  <span class="info-box-text info-box-text-fatura"></span>
                  <a id="detay_acilan_icmal_faturalari" style="cursor: pointer;" class="small-box-footer">
                    <i class="fa fa-arrow-circle-right"></i>
                    <span class="info-box-number" style="display: inline;font-size: 15px;" lang="en">Brief invoices</span> 
                </a>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div>
            <!-- aftersales dashboard data ilk blok son-->

            <!--hidden data block 1 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden1" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden1_title" lang="en"></h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block1_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block1_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block1" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 1 son-->
            
            <!-- aftersales dashboard data ikinci blok -->
            <div class="row">
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_1_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Open Orders</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_acik_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_2_container" class="small-box bg-man-ligth-grey bg-green">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Opened Orders</p>
                            
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-add-circle"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_acilan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_3_container" class="small-box bg-man-ligth-grey bg-yellow">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Closed Orders</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-close"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_4_container" class="small-box bg-man-ligth-grey bg-red">

                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Inventory</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_stoklar" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                        <!--<a onclick="return false;" class="small-box-footer bg-man-grey-small-box-footer"><i class="fa fa-arrow-circle-right"></i></a>-->
                    </div>

                </div><!-- ./col -->

            </div><!-- /.row -->
            <!-- aftersales dashboard data ikinci blok son -->
            
            <!--hidden data block 2 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_title" lang="en">Work order</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block2_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block2_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 2 son-->
            
            <!--hidden data stoklar block  -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_stoklar" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_stoklar_title" lang="en">Work order</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <!--<div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block2_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block2_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>-->
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                            
                        <table id="example" class="table table-striped table-bordered" class="display" style="width:100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>Stok Tutar</th>
                                    
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>Stok Tutar</th>
                                </tr>
                            </tfoot>
                        </table>
                            
                            
                          <!--<table  id="tt_grid_dynamic" title="Modul-Action  " ></table> -->
                          <!--<div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>-->
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data stoklar block son -->
            
            <!-- aftersales dashboard data üçüncü blok -->
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_header_arac_giris_sayilari_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Vehicle Entries</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-alert"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_arac_girisleri" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_header_downtime_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Downtime</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-time"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_downtime" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- aftersales dashboard data üçüncü blok son -->
            
            <!--hidden data block 3 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden3" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden3_title" lang="en">Work order</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block3_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block3_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block3" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 3 son-->
            
            <!--hidden data block 3_1 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden3_1" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden3_1_title" lang="en">Downtime</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <!--<div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block3_1_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block3_1_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>-->
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block3_1" style="min-width: 200px;  margin: 0 auto"></div>
                          
                          <table id="grid_downtime" class="table table-striped table-bordered" class="display" style="width:100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>DownTime</th>
                                    <th>Yıl</th>
                                    <th>Ay</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>DownTime</th>
                                    <th>Yıl</th>
                                    <th>Ay</th>
                                </tr>
                            </tfoot>
                        </table>
                          
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 3_1 son-->
            
            <!-- aftersales dashboard data verimlilik blok -->
            <div class="row">
                <div class="col-lg-6">
                  <div class="box" id="panel_productivity" >
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_productivity_title" lang="en">Customer first</h3> 
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" id="panel_productivity_detail" onclick="return false;" ><i class="fa fa-archive"></i></button>-->
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="gauge-container-verimlilik" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">   
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
                <div class="col-lg-6">
                  <div class="box" id="panel_kapasite" >
                    <div class="box-header with-border">
                        <h3 class="box-title" id="panel_kapasite_title" lang="en">Customer first</h3> 
                      <div class="box-tools pull-right"> 
                        <!--<button class="btn btn-box-tool" id="panel_kapasite_detail" onclick="return false;" ><i class="fa fa-archive"></i></button>-->
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="gauge-container-kapasite" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
                <!--<div class="col-lg-4">
                  <div class="box" id="panel_etkinlik" >
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_etkinlik_title" lang="en">Efficiency</h3>
                      <div class="box-tools pull-right">
                          <button class="btn btn-box-tool" id="panel_etkinlik_detail" onclick="return false;" ><i class="fa fa-archive"></i></button>
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <!--<div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="gauge-container-etkinlik" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      <!--</div><!-- /.row -->
                    <!--</div><!-- ./box-body -->
                    <!--<div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  <!--</div><!-- /.box -->
                <!--</div>-->
            </div><!-- /.row -->
            <!-- aftersales dashboard data verimlilik blok son -->
            
            <!--hidden data verimlilik blok -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden_verimlilik_blok" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden_verimlilik_blok_title" lang="en">Downtime</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <!--<div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block3_1_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block3_1_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>-->
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_verimlilik_blok" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data verimlilik blok son-->
            
             <!-- aftersales dashboard data yedek parça blok -->
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_yedek_parca_toplam_satis_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Total sales of spare parts</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_yedekparca_toplam_satis" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_yedek_parca_toplam_yag_satis_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Sale of spare parts oil</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_yedekparca_yag_satis" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- aftersales dashboard data yedek parça blok son -->
            
            <!--hidden data block yedek parça toplam satış -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden_yedek_parca_toplam_satis" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden_yedek_parca_toplam_satis_title" lang="en">Customer first</h3>
                      <div class="box-tools pull-right">
                          <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_yedek_parca_toplam_satis_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_yedek_parca_toplam_satis_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                         <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          <div id="container_hidden_yedek_parca_toplam_satis" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block yedek parça toplam satış son-->
            
            <!--hidden data block yedek parça yag satış -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden_yedek_parca_yag_satis" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden_yedek_parca_yag_satis_title" lang="en">Customer first</h3>
                      <div class="box-tools pull-right">
                          <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_yedek_parca_yag_satis_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_yedek_parca_yag_satis_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          <div id="container_hidden_yedek_parca_yag_satis" style="min-width: 200px;  margin: 0 auto"></div>
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;"> 
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block yedek parça yag satış son-->
            
            
            <!-- aftersales dashboard data karsılaştırma blok-->
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="info-box bg-man-blue">
                        <span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>
                        <div class="info-box-content" id="toplam_ciro_1_container">
                            <h3 style="margin-top: 12px;" >
                                <div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                          <span class="info-box-text "></span>
                          <span class="info-box-number" lang="en">The number of customers</span>
                          <div class="progress" id="toplam_musteri_container_progress_bar">
                            <div class="progress-bar" style="width: 100%"></div>
                          </div>
                          <span class="progress-description">
                            Bir önceki güne göre oran
                          </span>
                        </div><!-- /.info-box-content -->
                    </div>
                </div><!-- /.col -->
                <!--<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    
                    <div class="info-box  bg-man-blue">
                <span class="info-box-icon"><i class="ion-ios-chatbubble-outline"></i></span>
                <div class="info-box-content" id="toplam_ciro_2_container">
                    <h3 style="margin-top: 12px;">
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                    </h3>
                  <span class="info-box-text"></span>
                  <a id="detay_acilan_ciro" style="cursor: pointer;color: #fff;" class="small-box-footer">
                        <i class="fa fa-arrow-circle-right"></i>
                        <span class="info-box-number" style="display: inline;" lang="en"></span> 
                    </a>
                  <div class="progress" id="toplam_ciro_container_progress_bar">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    
                  </span>
                </div><!-- /.info-box-content -->
              <!--</div>
                </div><!-- /.col -->
                
            </div>
            <!-- aftersales dashboard data karsılaştırma blok son-->
            
            <!--hidden data block 4 -->
            <!--<div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <!--<div class="col-md-12">
                  <div class="box" id="panel_hidden4" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden4_title">Cirolar</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <!--<div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block4_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block4_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <!--<div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block4" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      <!--</div><!-- /.row -->
                    <!--</div><!-- ./box-body -->
                    <!--<div class="box-footer" style="display: block;">
                    </div><!-- /.box-footer -->
                  <!--</div><!-- /.box -->
                <!--</div>
            <!--</section>  -->
            <!--</div>
            <!--hidden data block 4 son-->
            
            <!-- aftersales dashboard data cirolar blok -->
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_atolye_cirosu_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Workshop sales</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-cart"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_atolye_cirosu" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_garanti_cirosu_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Warranty sales</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-cart""></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_garanti_cirosu" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_direk_satis_cirosu_container" class="small-box bg-man-ligth-grey bg-aqua ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Direct sales</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-cart""></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_direk_satis_cirosu" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- aftersales dashboard data cirolar blok son -->
            
            <!--hidden data block atolye cirosu -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden_atolye_cirosu" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden_atolye_cirosu_title" lang="en">Workshop sales</h3>
                      <div class="box-tools pull-right">
                          <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_atolye_cirosu_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_atolye_cirosu_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                         <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          <div id="container_hidden_atolye_cirosu" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block atolye cirosu son-->
            
            <!--hidden data block garanti cirosu -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden_garanti_cirosu" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden_garanti_cirosu_title" lang="en">Warranty sales</h3>
                      <div class="box-tools pull-right">
                          <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_garanti_cirosu_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_garanti_cirosu_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                         <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          <div id="container_hidden_garanti_cirosu" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block garanti cirosu son-->
            
            <!--hidden data block direk satış cirosu -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden_direk_satis_cirosu" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden_direk_satis_cirosu_title" lang="en">Direct sales</h3>
                      <div class="box-tools pull-right">
                          <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_direk_satis_cirosu_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_direk_satis_cirosu_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                         <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          <div id="container_hidden_direk_satis_cirosu" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block direk satış cirosu son-->
            
            
            <!-- aftersales müşteri memnuniyeti blok -->
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_header_MM_CSI_container" class="small-box bg-man-yellow ">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >(CSI)
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Customer first</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-checkmark-circle"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_CSI" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <!-- small box -->
                    <div id="toplam_header_MM_CXI_container" class="small-box bg-man-yellow  ">
                        <div class="inner" >
                            <h3 class="man-header-red"><div class="overlay" >(CXI)
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Customer first</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-android-checkmark-circle"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_CXI" class="small-box-footer bg-man-grey-small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- aftersales müşteri memnuniyeti blok son -->
            
            <!--hidden data block müşteri memnuniyeti CSI -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden_MM_CSI" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden_MM_CSI_title" lang="en">Customer first</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          <div id="container_hidden_MM_CSI" style="min-width: 200px;  margin: 0 auto"></div>
                          <table id="grid_CSI" class="table table-striped table-bordered" class="display" style="width:100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>Ay</th>
                                    <th>Yıl</th>
                                    <th>Memnuniyet</th>
                                    <!--<th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>-->
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>Ay</th>
                                    <th>Yıl</th>
                                    <th>Memnuniyet</th>
                                    <!--<th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>-->
                                </tr>
                            </tfoot>
                        </table>
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block müşteri memnuniyeti CSI son-->
            
            <!--hidden data block müşteri memnuniyeti CXI -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden_MM_CXI" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden_MM_CXI_title" lang="en">Customer first</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          <div id="container_hidden_MM_CXI" style="min-width: 200px;  margin: 0 auto"></div>
                          <table id="grid_CXI" class="table table-striped table-bordered" class="display" style="width:100%">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>Ay</th>
                                    <th>Yıl</th>
                                    <th>Memnuniyet</th>
                                    <!--<th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>-->
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th>ID</th>
                                    <th>Servis Adı</th>
                                    <th>Ay</th>
                                    <th>Yıl</th>
                                    <th>Memnuniyet</th>
                                    <!--<th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>
                                    <th>Ay/Yıl</th>-->
                                </tr>
                            </tfoot>
                        </table>
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block müşteri memnuniyeti CXI son-->
            
            <!--Sales dashboard data ilk blok-->
            <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12 " ">
                <!--<div class="flipper" >-->
                    <div class="info-box overlay front">
                  
                    <span class="info-box-icon  bg-man-yellow"><i class="ion ion-ios-gear-outline"></i></span>
                    <div class="info-box-content" id="toplam_sales_1_container">
                        <h3>
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                      <span class="info-box-text info-box-text-fatura"></span>
                      <span class="info-box-number" lang="en">MTBTR sales</span>

                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-man-red"><i class="ion ion-ios-information"></i></span>
                <div class="info-box-content" id="toplam_sales_2_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                    </h3>
                  <span class="info-box-text info-box-text-fatura"></span>
                  <span class="info-box-number" lang="en">MTBTR stocks</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-man-yellow"><i class="fa fa-gears "></i></span>
                <div class="info-box-content" id="toplam_sales_3_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                  </h3>
                  <span class="info-box-text info-box-text-fatura"></span>
                  <a id="detay_acilan_bayi_stoklari" style="cursor: pointer;" class="small-box-footer">
                    <i class="fa fa-arrow-circle-right"></i>
                    <span class="info-box-number" style="display: inline;" lang="en">Dealer stocks</span> 
                  </a>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-man-red"><i class="ion ion ion-android-time"></i></span>
                <div class="info-box-content" id="toplam_sales_4_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                  </h3>
                  <span class="info-box-text info-box-text-fatura" ></span>
                  <span class="info-box-number" lang="en">Dealer invoices</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div>
            <!--Sales dashboard data ilk blok son-->
            
            <!--hidden data block 5 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden5" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden5_title">Bayi Stokları</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block5" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 5 son-->
            
            <!-- sales dashboard data ikinci blok -->
             <div class="row">
                <div class="col-lg-6 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_sales_block2_1_container" class="small-box bg-aqua bg-man-ligth2-grey">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Dealer oppurtunities</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a onclick="return false;" class="small-box-footer"><i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-6 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_sales_block2_2_container" class="small-box bg-aqua bg-man-ligth2-grey">
                        <div class="inner">
                            <h3 class="man-header-red"><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Dealer activities(today)</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a onclick="return false;" class="small-box-footer"><i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- sales dashboard data ikinci blok son -->
            
            <!-- Main row -->
            <div class="row">
            
                <section class="col-lg-6 connectedSortable">
                    
                    <!-- TO DO List -->
                    <div id='todolistboxServis' class="box ">
                        <div class="box-header">
                            <i class="ion ion-clipboard"></i>
                            <h3 class="box-title" lang="en">Last orders <span lang="en">Dealer</span></h3>
                            <div class="box-tools pull-right">
                                 <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                 <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div><!-- /.box-header -->
                        <div class="box-body" id="loader_test">
                            <ul class="todo-list" id="servisFillerUL">
                                <li>
                                    <!-- drag handle -->
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!-- checkbox -->
                                    <input type="checkbox" value="" name=""/>
                                    <!-- todo text -->
                                    <span data-fill="true" class="text">test</span>
                                    <!-- Emphasis label -->
                                    <small data-fill-number="true" class="label label-danger"><i class="fa fa-clock-o"></i> </small>
                                    <!-- General tools such as edit or delete-->
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span  data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-info"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">   
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-warning"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-success"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-primary"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-default"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                            </ul>
                        </div><!-- /.box-body -->
                        <div class="box-footer clearfix no-border">
                            <!--<button class="btn btn-default pull-right"><i class="fa fa-plus"></i> Ekle</button>-->
                        </div>
                    </div><!-- /.box -->

                    


                </section><!-- /.Left col -->
                <!-- right col (We are only adding the ID to make the widgets sortable)-->
                <section class="col-lg-6 connectedSortable">

                    <!-- TO DO List -->
                    <div id='todolistboxServisMusteri' class="box ">
                        <div class="box-header">
                            <i class="ion ion-clipboard"></i>
                            <h3 class="box-title" lang="en">Last orders <span lang="en">Customer</span></h3>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <ul class="todo-list" id="servisMusteriFillerUL">
                                <li>
                                    <!-- drag handle -->
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!-- checkbox -->
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <!-- todo text -->
                                    <span data-fill="true" class="text"></span>
                                    <!-- Emphasis label -->
                                    <small data-fill-number="true" class="label label-danger"><i class="fa fa-clock-o"></i> </small>
                                    <!-- General tools such as edit or delete-->
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span  data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-info"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">   
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-warning"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-success"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-primary"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-default"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                            </ul>
                        </div><!-- /.box-body -->
                        <div class="box-footer clearfix no-border">
                            <!--<button class="btn btn-default pull-right"><i class="fa fa-plus"></i> Ekle</button>-->
                        </div>
                    </div>
                    
                    

                </section><!-- right col -->
            </div><!-- /.row (main row) -->

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php /*echo $this->partial('partials/admincontrolasidepartial.phtml');*/ ?>
    <!-- Control Sidebar son-->   
    
</div><!-- ./wrapper -->
<!-- sayfa içine yazılan js'ler ekleniyor-->
<script src="<?php echo $this->basePath('jsinline/admin.js') ?>" type="text/javascript"></script>

 <!-- easyui implementation -->
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/jquery.easyui.min.js') ?>"></script>
<script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/locale/easyui-lang-tr.js') ?>"></script>
<script src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/src/datagrid-filter.js') ?>"></script>

<!-- ddslick select plugin ekleniyor-->
<script src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.js') ?>" type="text/javascript"></script>

<!-- tagCabin Js-->
<script src="<?php echo $this->basePath('plugins/zeynel/tag-cabin/tag-cabin.js') ?>" type="text/javascript"></script>  

<!-- jquery-number plugin-->
<script src="<?php echo $this->basePath('plugins/jquery-number/jquery.number.min.js') ?>" type="text/javascript"></script>

<!-- jquery data-table -->
<script src="<?php echo $this->basePath('plugins/jquery-datatable/datatables.min.js') ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('plugins/jquery-datatable/DataTables-1.10.16/js/dataTables.bootstrap.min.js') ?>" type="text/javascript"></script>
