<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar" >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1> Kamyon Satış Durumu
                <?php //echo $this->translate('Imalat Control Panel') ?>
                <small></small>
            </h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content" id="test">
            
            
            <!-- kamyon satış block 1-->
            <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-red">
                <span class="info-box-icon"><i class="fa fa-calendar"></i></span>
                <div class="info-box-content">
                    
                  <span class="info-box-text" id="kamyon_satis_baslik_block1_1">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                  </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block1_1"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-color-sea">
                <span class="info-box-icon"><i class="fa fa-share-square-o"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block1_2">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block1_2"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-green">
                <span class="info-box-icon"><i class="fa fa-share-square-o"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block1_3">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block1_3"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-yellow">
                <span class="info-box-icon"><i class="fa fa-dashboard"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block1_4">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block1_4"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div>
          <!-- kamyon satış block 1 son-->
            
          <!-- kamyon satış block 2-->
            <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-green">
                <span class="info-box-icon"><i class="fa fa-dashboard"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block2_1">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block2_1"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-aqua-active">
                <span class="info-box-icon"><i class="fa fa-dashboard"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block2_2">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block2_2"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-color-dark">
                <span class="info-box-icon"><i class="fa fa-dashboard"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block2_3">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block2_3"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-aqua-active">
                <span class="info-box-icon"><i class="fa fa-dashboard"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block2_4">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block2_4"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div>
          <!-- kamyon satış block 2 son-->
            
          <!-- kamyon satış block 3-->
            <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-yellow-active">
                <span class="info-box-icon"><i class="fa fa-clock-o"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block3_1">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block3_1"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-red-active">
                <span class="info-box-icon"><i class="fa fa-clock-o"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block3_2">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block3_2"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-green-active">
                <span class="info-box-icon"><i class="fa fa-clock-o"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block3_3">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block3_3"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box bg-aqua-active">
                <span class="info-box-icon"><i class="fa fa-gears"></i></span>
                <div class="info-box-content">
                    <span class="info-box-text" id="kamyon_satis_baslik_block3_4">
                        <h3 style="margin-top: 12px;">
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                    </span>
                  <span class="info-box-number" id="kamyon_satis_deger_block3_4"></span>
                  <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    <!--70% Increase in 30 Days-->
                  </span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div>
          <!-- kamyon satış block 3 son-->
            

            
    </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php echo $this->partial('admincontrolasidepartial.phtml'); ?>
    <!-- Control Sidebar son--> 
</div><!-- ./wrapper -->

    <!-- sayfa içine yazılan js'ler ekleniyor-->
    <script src="<?php echo $this->basePath('jsinline/admin_ksal.js') ?>" type="text/javascript"></script>