<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="ln" type="hidden"  value="tr"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>


    <div class="wrapper">

        <!-- admin header -->
        <?php echo $this->partial('adminheaderpartial.phtml'); ?>
        <!-- admin header son-->

        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar" >
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- Sidebar user panel -->
                <?php echo $this->partial('adminasideuserpanelpartial.phtml'); ?>

                <!-- search form -->
                <?php echo $this->partial('adminasidesearchformpartial.phtml'); ?>
                <!-- /.search form -->

                <!-- sidebar menu: : style can be found in sidebar.less -->
                <?php echo $this->partial('adminmenupartial.phtml'); ?>

            </section>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <h1>
                    <?php echo $this->translate('Imalat Control Panel') ?>
                    Kullanıcı Menüsü İşlemleri
                    <small></small>
                </h1>
                <!-- admin breadcrumb panel -->
                <?php echo $this->partial('adminbreadcrumbpartial.phtml'); ?>
                <!-- admin breadcrumb panel son-->
            </section>
            <!-- Main content -->
            <section class="content">
                <!--first collapsible panel row -->
                <div class="row">
                    <!--first collapsible panel width, single column-->
                    <div class="col-lg-12">
                        <!--arrange first panel color to blue by assigning primary class-->
                        <div id="loading-image-crud" class="box box-primary">
                            <!--First panel Header-->
                            <div class="box-header with-border">                                                    
                                <h3 class="box-title"> Kullanıcı tiplerine göre menüler </h3>
                                <!--Panel 1 collapse button-->
                                <div class="box-tools pull-right">
                                    <button class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse"><i class="fa fa-minus"></i></button>
                                </div><!--/. button div-->
                            </div><!--/. panel 1 header div-->
                            <!--Panel 1 contents-->
                            <div  class="box-body">       
                                <form id='menuForm' method="get" class="form-horizontal">  
                                    <div class="alert alert-danger alert-dismissable">
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                                        <h4><i class="icon fa fa-info"></i> Menü İşlemlerine başlamak için 'Kullanıcı Rolü' seçiniz!</h4>
                                        Menü işlemleri kullanıcı rolü bazlı olarak yapılmaktadır.
                                            Öncelikle 'Kullanıcı Rolü' belirleyiniz, Menü öğelerini gösteren
                                            yapı aktif olacaktır.
                                    </div>
                                    <div id="roleFormBlock" class="box box-primary" style="padding-top: 20px;">
                                    <!--Easyui tree  div start-->
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Menü</label>
                                            <div class="col-sm-10">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-code-fork"></i>
                                                    </div>
                                                    <div class="inner">
                                                        <div id="loading-image">
                                                        <ul id="tt_tree_menu" class="easyui-tree" ></ul> 
                                                        </div>
                                                    </div>                                                       
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Kullanıcı Rolleri</label>
                                            <div class="col-sm-10">
                                                <div class="input-group"> 
                                                  <span class="input-group-addon"><i class="fa fa-tag"></i></span>
                                                  <div id="dropdownRoles" ></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Menü Tipleri</label>
                                            <div class="col-sm-10">
                                                <div class="input-group"> 
                                                  <span class="input-group-addon"><i class="fa fa-tag"></i></span>
                                                  <div id="dropdownMenuTypes" ></div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Menü</label>
                                            <div class="col-sm-10">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-hand-o-right"></i>
                                                    </div>
                                                    <input data-prompt-position="topLeft:70" class="form-control validate[required]" type="text" name="menu_name" id="menu_name" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">İngilizce Menü</label>
                                            <div class="col-sm-10">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-hand-o-right"></i>
                                                    </div>
                                                    <input data-prompt-position="topLeft:70" class="form-control validate[required]" type="text" name="menu_name_eng" id="menu_name_eng" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Url</label>
                                            <div class="col-sm-10">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-hand-o-right"></i>
                                                    </div>
                                                    <input data-prompt-position="topLeft:70" class="form-control validate[required]" type="text" name="url" id="url" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Menü İkon</label>
                                            <div class="col-sm-10">
                                                <div class="input-group">
                                                    <div class="input-group-addon">
                                                        <i class="fa fa-hand-o-right"></i>
                                                    </div>
                                                    <input data-prompt-position="topLeft:70" value="fa-circle-o" class="form-control validate[required]" type="text" name="icon_class" id="icon_class" />
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-10 col-sm-offset-2">
                                                <button id="insertMenu" class="btn btn-primary" type="submit" onclick="return insertMenuRootWrapper(event);"><i class="fa fa-save"></i>  Ana Kategoriye Menü Kaydet </button>
                                                <button id="updateMenu" class="btn btn-flat" type="submit" onclick="return updateMenuWrapper(event);" disabled><i class="fa fa-gears"></i> Güncelle </button>
                                                <button id="resetForm" class="btn btn-flat" type="reset" onclick="regulateButtons();" ><i class="fa fa-remove"></i> Reset </button>
                                            </div>
                                        </div>
                                    </div> 
                                </form>   
                            </div><!-- /.box-body -->
                        </div><!--/. primary box div-->
                    </div><!--/. first panel single column div -->
                </div><!-- / first panel row-->

                

            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->
        <!-- footer --> 
        <?php echo $this->partial('adminfooterpartial.phtml'); ?>
        <!-- footerson--> 

        <!-- Control Sidebar --> 
        <?php echo $this->partial('admincontrolasidepartial.phtml'); ?>
        <!-- Control Sidebar son--> 
    </div><!-- ./wrapper -->

    <!-- sayfa içine yazılan js'ler ekleniyor-->
    <script src="<?php echo $this->basePath('jsinline/admin_menu.js') ?>" type="text/javascript"></script>
    
    <!-- easyui implementation -->
    <script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/jquery.easyui.min.js') ?>"></script>
    <script language="JavaScript" type="text/javascript" src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/locale/easyui-lang-tr.js') ?>"></script>
    <script src="<?php echo $this->basePath('plugins/jquery-easyui-1.3.3/src/datagrid-filter.js') ?>"></script>
    
    <!-- Form validation js -->
    <script src="<?php  echo $this->basePath('plugins/validationEngine/jquery.validationEngine-tr.js'); ?>" type="text/javascript"></script>
    <script src="<?php echo $this->basePath('plugins/validationEngine/jquery.validationEngine.js') ?>" type="text/javascript"></script>
    
    <!-- ddslick select plugin ekleniyor-->
    <script src="<?php echo $this->basePath('plugins/bootstrap-select-ddslick/js/ddslick.js') ?>" type="text/javascript"></script>
        
    <!-- tagCabin Js-->
    <script src="<?php echo $this->basePath('plugins/zeynel/tag-cabin/tag-cabin.js') ?>" type="text/javascript"></script>               
