<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar" >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1> Marka Satış Adetleri
                <?php //echo $this->translate('Imalat Control Panel') ?>
                <small></small>
            </h1>
            <!-- admin breadcrumb panel -->
            <?php echo $this->partial('adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content">
            

            
            
            <!-- aftersales dashboard data karsılaştırma blok-->
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="info-box bg-yellow">
                        <span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>
                        <div class="info-box-content" id="toplam_ciro_1_container">
                            <h3 style="margin-top: 12px;">
                                <div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                          <span class="info-box-text"></span>
                          <span class="info-box-number"></span>
                          <div class="progress" id="toplam_musteri_container_progress_bar">
                            <div class="progress-bar" style="width: 100%"></div>
                          </div>
                          <span class="progress-description">
                            Bir önceki güne göre oran
                          </span>
                        </div><!-- /.info-box-content -->
                    </div>
                </div><!-- /.col -->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    
                    <div class="info-box bg-aqua">
                <span class="info-box-icon"><i class="ion-ios-chatbubble-outline"></i></span>
                <div class="info-box-content" id="toplam_ciro_2_container">
                    <h3 style="margin-top: 12px;">
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                    </h3>
                  <span class="info-box-text"></span>
                  <span class="info-box-number"></span>
                  <div class="progress" id="toplam_ciro_container_progress_bar">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    Bir önceki güne göre oran
                  </span>
                </div><!-- /.info-box-content -->
              </div>
                    
                    
                    
                    
                    
                    
                </div><!-- /.col -->
                
            </div>
            <!-- aftersales dashboard data karsılaştırma blok son-->
            
            <!--Marka Satış Adetleri - 2016-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box">
                    <div class="box-header with-border">
                      <h3 class="box-title">Marka Satış Adetleri - 2016</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-lg-12">
                          <div class="chart">
                              <div id="container_satis_2016" style="min-width: 250px;width: 100%;  margin: 0 auto"></div>
                          </div>
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      <div class="row">
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                            <h5 class="description-header">$35,210.43</h5>
                            <span class="description-text">TOTAL REVENUE</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                            <h5 class="description-header">$10,390.90</h5>
                            <span class="description-text">TOTAL COST</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                            <h5 class="description-header">$24,813.53</h5>
                            <span class="description-text">TOTAL PROFIT</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block">
                            <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                            <h5 class="description-header">1200</h5>
                            <span class="description-text">GOAL COMPLETIONS</span>
                          </div><!-- /.description-block -->
                        </div>
                      </div><!-- /.row -->
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--Marka Satış Adetleri - 2016 son-->
            
            
            
            <!--Marka Satış Adetleri - 2017-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box">
                    <div class="box-header with-border">
                      <h3 class="box-title">Marka Satış Adetleri - 2017</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-lg-12">
                          
                          <div class="chart">
                              <div id="container_satis_2017" style="min-width: 250px;width: 100%;  margin: 0 auto"></div>
                          </div>
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      <div class="row">
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                            <h5 class="description-header">$35,210.43</h5>
                            <span class="description-text">TOTAL REVENUE</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                            <h5 class="description-header">$10,390.90</h5>
                            <span class="description-text">TOTAL COST</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                            <h5 class="description-header">$24,813.53</h5>
                            <span class="description-text">TOTAL PROFIT</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block">
                            <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                            <h5 class="description-header">1200</h5>
                            <span class="description-text">GOAL COMPLETIONS</span>
                          </div><!-- /.description-block -->
                        </div>
                      </div><!-- /.row -->
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--Marka Satış Adetleri - 2017 son-->
            
            
            <!--Marka Satış Adetleri all-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box">
                    <div class="box-header with-border">
                      <h3 class="box-title">Marka Satış Adetleri - 2017</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-lg-12">
                          
                          <div class="chart">
                              <div id="container_satis_all" style="min-width: 250px;width: 100%;  margin: 0 auto"></div>
                          </div>
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      <div class="row">
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                            <h5 class="description-header">$35,210.43</h5>
                            <span class="description-text">TOTAL REVENUE</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                            <h5 class="description-header">$10,390.90</h5>
                            <span class="description-text">TOTAL COST</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                            <h5 class="description-header">$24,813.53</h5>
                            <span class="description-text">TOTAL PROFIT</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block">
                            <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                            <h5 class="description-header">1200</h5>
                            <span class="description-text">GOAL COMPLETIONS</span>
                          </div><!-- /.description-block -->
                        </div>
                      </div><!-- /.row -->
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--Marka Satış Adetleri all son-->
            
               <!--Marka Satış Adetleri aylik-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box">
                    <div class="box-header with-border">
                      <h3 class="box-title">MAN Araç Satış</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-lg-12">
                          
                          <div class="chart">
                              <div id="container_satis_monthly" style="min-width: 250px;width: 100%;  margin: 0 auto"></div>
                          </div>
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      <div class="row">
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                            <h5 class="description-header">$35,210.43</h5>
                            <span class="description-text">TOTAL REVENUE</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                            <h5 class="description-header">$10,390.90</h5>
                            <span class="description-text">TOTAL COST</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                            <h5 class="description-header">$24,813.53</h5>
                            <span class="description-text">TOTAL PROFIT</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block">
                            <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                            <h5 class="description-header">1200</h5>
                            <span class="description-text">GOAL COMPLETIONS</span>
                          </div><!-- /.description-block -->
                        </div>
                      </div><!-- /.row -->
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--Marka Satış Adetleri aylik son-->

            
            
            
           
            

            <!-- Main row -->
            <div class="row">
            
                <section class="col-lg-12 ">
                    
                    <!-- quick email widget -->
                    <div class="box box-info">
                        <div class="box-header">
                            <i class="fa fa-envelope"></i>
                            <h3 class="box-title">E-posta</h3>
                            <!-- tools box -->
                            <div class="pull-right box-tools">
                                <button class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                            </div><!-- /. tools -->
                        </div>
                        <div class="box-body">
                            <form action="#" method="post">
                                <div class="form-group">
                                    <input type="email" class="form-control" name="Kime" placeholder="Kime:"/>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="Konu" placeholder="Konu"/>
                                </div>
                                <div>
                                    <textarea class="textarea" placeholder="Mesaj" style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>
                            </form>
                        </div>
                        <div class="box-footer clearfix">
                            <button class="pull-right btn btn-default" id="sendEmail">Gönder <i class="fa fa-arrow-circle-right"></i></button>
                        </div>
                    </div>
                </section><!-- /. col -->
                
            </div><!-- /.row (main row) -->

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php echo $this->partial('admincontrolasidepartial.phtml'); ?>
    <!-- Control Sidebar son--> 
</div><!-- ./wrapper -->

