<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>

<?php // partial.phtml ?>
<form action="#" method="get" class="sidebar-form">
    <div class="input-group">
        <input id="menu_search" type="text" name="q" class="form-control" lang="en" placeholder="Search"/>
        <span class="input-group-btn">
            <button type='button' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
        </span>
    </div>
</form>