<?php // partial.phtml ?>

<li class="dropdown language-selector" id='languages'>                          
                        <a  style='cursor:pointer;' onclick="return false;" class="dropdown-toggle" data-toggle="dropdown" data-close-others="true">
                            <!--<img src="<?php echo $this->basePath('img/flag-uk.png') ?>"-->
                            <span id="default_lang" class="logo-mini"></span>
                        </a>
                        <ul id="lang_list_container"   class="dropdown-menu pull-right ">
                            <!--<li class="active">
                                <a href="#" onclick="window.lang.change('en'); window.location.href= '../en/admin';">
                                    <span class="logo-mini">EN</span>
                                    <span>English</span>
                                </a>
                            </li>
                            <li>
                                <a href="#" onclick="window.lang.change('tr'); window.location.href= '../tr/admin';">
                                    <span class="logo-mini">TR</span>
                                    <span>Türkçe</span>
                                </a>
                            </li>
                            <li >
                                <a href="#" onclick="window.lang.change('th'); window.location.href= '../ru/admin';">
                                    <span class="logo-mini">RU</span>
                                    <span>Pу́сский</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="logo-mini">DE</span>
                                    <span>Deutsch</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="logo-mini">FR</span>
                                    <span>Français</span>
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    <span class="logo-mini">AR</span>
                                    <span>العربية</span>
                                </a>
                            <li>
                                <a href="#">
                                    <span class="logo-mini">FA</span>
                                    <span>فارسی</span>
                                </a>
                            </li>-->
                        </ul>
                    </li>