<input id="requestUriRegulated" type="hidden"  value="<?php echo $this->requestUriRegulated; ?>"></input>
<input id="langCode" type="hidden"  value="<?php echo $this->langCode; ?>"></input>
<input id="pk" type="hidden"  value="<?php echo $this->publicKey; ?>"></input>
<input id="controller" type="hidden"  value="<?php echo $this->layout()->controller; ?>"></input>
<input id="module" type="hidden"  value="<?php echo $this->layout()->module; ?>"></input>

<div class="wrapper">

    <!-- admin header -->
    <?php echo $this->partial('partials/adminheaderpartial.phtml'); ?>
    <!-- admin header son-->
    
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar" >
        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">
            <!-- Sidebar user panel -->
            <?php echo $this->partial('partials/adminasideuserpanelpartial.phtml'); ?>
            
            <!-- search form -->
            <?php echo $this->partial('partials/adminasidesearchformpartial.phtml'); ?>
            <!-- /.search form -->
            
            <!-- sidebar menu: : style can be found in sidebar.less -->
            <?php echo $this->partial('partials/adminmenupartial.phtml'); ?>

        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1 lang="en">Management Dashboard</h1>
            <!-- admin breadcrumb panel -->
                <?php echo $this->partial('partials/adminbreadcrumbpartial.phtml'); ?>
            <!-- admin breadcrumb panel son-->
        </section>

        <!-- Main content -->
        <section class="content">
            
            <!-- aftersales dashboard data ilk blok -->
            <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12 flip-container " ontouchstart="this.classList.toggle('hover');">
                    <div class="info-box overlay front">
                  
                    <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>
                    <div class="info-box-content" id="toplam_fatura_1_container">
                        <h3>
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                      <span class="info-box-text info-box-text-fatura"></span>
                      <a id="detay_acilan_alis_faturalari" style="cursor: pointer;" class="small-box-footer">
                          <i class="fa fa-arrow-circle-right"></i>
                          <span class="info-box-number" style="display: inline;font-size: 15px;" lang="en">Purchase invoices</span> 
                      </a>
                      
                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-red"><i class="ion ion-ios-information"></i></span>
                <div class="info-box-content" id="toplam_fatura_2_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                    </h3>
                    <span class="info-box-text info-box-text-fatura"></span>
                    <a id="detay_acilan_isemri_faturalari" style="cursor: pointer;" class="small-box-footer">
                        <i class="fa fa-arrow-circle-right"></i>
                        <span class="info-box-number" style="display: inline;font-size: 15px;" lang="en">Business order invoices</span> 
                    </a>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-green"><i class="fa fa-gears "></i></span>
                <div class="info-box-content" id="toplam_fatura_3_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                  </h3>
                  <span class="info-box-text info-box-text-fatura"></span>
                  <a id="detay_acilan_satis_faturalari" style="cursor: pointer;" class="small-box-footer">
                        <i class="fa fa-arrow-circle-right"></i>
                        <span class="info-box-number" style="display: inline;font-size: 15px;" lang="en">Sales invoices</span> 
                    </a>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-yellow"><i class="ion ion ion-android-time"></i></span>
                <div class="info-box-content" id="toplam_fatura_4_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                  </h3>
                  <span class="info-box-text info-box-text-fatura"></span>
                  <a id="detay_acilan_icmal_faturalari" style="cursor: pointer;" class="small-box-footer">
                    <i class="fa fa-arrow-circle-right"></i>
                    <span class="info-box-number" style="display: inline;font-size: 15px;" lang="en">Brief invoices</span> 
                </a>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div>
            <!-- aftersales dashboard data ilk blok son-->

            <!--hidden data block 1 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden1" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden1_title"></h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block1_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block1_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block1" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 1 son-->
            
            <!-- aftersales dashboard data ikinci blok -->
            <div class="row">
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_1_container" class="small-box bg-aqua">
                        <div class="inner">
                            <h3><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Open Orders</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a href="#" class="small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_2_container" class="small-box bg-green">
                        <div class="inner">
                            <h3><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Opened Orders</p>
                            
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_acilan_is_emirleri" class="small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_3_container" class="small-box bg-yellow">
                        <div class="inner">
                            <h3><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Closed Orders</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-briefcase"></i>
                        </div>
                        <a style="cursor: pointer;" id="detay_kapanan_is_emirleri" class="small-box-footer" lang="en">Details&nbsp;&nbsp;<i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-3 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_header_4_container" class="small-box bg-red">

                        <div class="inner">
                            <h3><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Total Spare Parts</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-stats-bars"></i>
                        </div>
                        <a onclick="return false;" class="small-box-footer"><i class="fa fa-arrow-circle-right"></i></a>
                    </div>

                </div><!-- ./col -->

            </div><!-- /.row -->
            <!-- aftersales dashboard data ikinici blok son -->
            
            <!--hidden data block 2 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" lang="en">Work order</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block2_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block2_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_satis_all" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      <div class="row">
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                            <h5 class="description-header">$35,210.43</h5>
                            <span class="description-text">TOTAL REVENUE</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                            <h5 class="description-header">$10,390.90</h5>
                            <span class="description-text">TOTAL COST</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                            <h5 class="description-header">$24,813.53</h5>
                            <span class="description-text">TOTAL PROFIT</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block">
                            <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                            <h5 class="description-header">1200</h5>
                            <span class="description-text">GOAL COMPLETIONS</span>
                          </div><!-- /.description-block -->
                        </div>
                      </div><!-- /.row -->
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 2 son-->
            
            <!-- aftersales dashboard data karsılaştırma blok-->
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    <div class="info-box bg-yellow">
                        <span class="info-box-icon"><i class="ion ion-ios-pricetag-outline"></i></span>
                        <div class="info-box-content" id="toplam_ciro_1_container">
                            <h3 style="margin-top: 12px;">
                                <div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                          <span class="info-box-text"></span>
                          <span class="info-box-number" lang="en">The number of customers</span>
                          <div class="progress" id="toplam_musteri_container_progress_bar">
                            <div class="progress-bar" style="width: 100%"></div>
                          </div>
                          <span class="progress-description">
                            Bir önceki güne göre oran
                          </span>
                        </div><!-- /.info-box-content -->
                    </div>
                </div><!-- /.col -->
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                    
                    <div class="info-box bg-aqua">
                <span class="info-box-icon"><i class="ion-ios-chatbubble-outline"></i></span>
                <div class="info-box-content" id="toplam_ciro_2_container">
                    <h3 style="margin-top: 12px;">
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                    </h3>
                  <span class="info-box-text"></span>
                  <a id="detay_acilan_ciro" style="cursor: pointer;color: #fff;" class="small-box-footer">
                        <i class="fa fa-arrow-circle-right"></i>
                        <span class="info-box-number" style="display: inline;" lang="en"></span> 
                    </a>
                  <div class="progress" id="toplam_ciro_container_progress_bar">
                    <div class="progress-bar" style="width: 100%"></div>
                  </div>
                  <span class="progress-description">
                    
                  </span>
                </div><!-- /.info-box-content -->
              </div>
                    
                    
                    
                    
                    
                    
                </div><!-- /.col -->
                
            </div>
            <!-- aftersales dashboard data karsılaştırma blok son-->
            
            <!--hidden data block 3 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden3" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden3_title">Cirolar</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <div class="btn-group open">
                            <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <i class="fa fa-calendar"></i>
                            </button>
                            <ul class="dropdown-menu" role="menu">
                              <li><a id='hidden_block3_month' lang="en">Last month</a></li>
                              <li class="divider"></li>
                              <li><a id='hidden_block3_year' lang="en">Last 1 year</a></li>
                            </ul>
                         </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block3" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 3 son-->
            
            <!--Graph data blok-->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box">
                    <div class="box-header with-border">
                      <h3 class="box-title">Monthly Recap Report</h3>
                      <div class="box-tools pull-right">
                        <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                        <div class="btn-group">
                          <button class="btn btn-box-tool dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i></button>
                          <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                          </ul>
                        </div>
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-8">
                          <p class="text-center">
                            <strong>Sales: 1 Jan, 2014 - 30 Jul, 2014</strong>
                          </p>
                          <div class="chart">
                              <div id="timeSeries" style="min-width: 310px;width: 100%; /*height: 400px;*/ margin: 0 auto"></div>
                          </div>
                        </div><!-- /.col -->
                        <div class="col-md-4">
                          <p class="text-center">
                            <strong>Goal Completion</strong>
                          </p>
                          <div class="progress-group">
                            <span class="progress-text">Add Products to Cart</span>
                            <span class="progress-number"><b>160</b>/200</span>
                            <div class="progress sm">
                              <div class="progress-bar progress-bar-aqua" style="width: 80%"></div>
                            </div>
                          </div><!-- /.progress-group -->
                          <div class="progress-group">
                            <span class="progress-text">Complete Purchase</span>
                            <span class="progress-number"><b>310</b>/400</span>
                            <div class="progress sm">
                              <div class="progress-bar progress-bar-red" style="width: 80%"></div>
                            </div>
                          </div><!-- /.progress-group -->
                          <div class="progress-group">
                            <span class="progress-text">Visit Premium Page</span>
                            <span class="progress-number"><b>480</b>/800</span>
                            <div class="progress sm">
                              <div class="progress-bar progress-bar-green" style="width: 80%"></div>
                            </div>
                          </div><!-- /.progress-group -->
                          <div class="progress-group">
                            <span class="progress-text">Send Inquiries</span>
                            <span class="progress-number"><b>250</b>/500</span>
                            <div class="progress sm">
                              <div class="progress-bar progress-bar-yellow" style="width: 80%"></div>
                            </div>
                          </div><!-- /.progress-group -->
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                      <div class="row">
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 17%</span>
                            <h5 class="description-header">$35,210.43</h5>
                            <span class="description-text">TOTAL REVENUE</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-yellow"><i class="fa fa-caret-left"></i> 0%</span>
                            <h5 class="description-header">$10,390.90</h5>
                            <span class="description-text">TOTAL COST</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block border-right">
                            <span class="description-percentage text-green"><i class="fa fa-caret-up"></i> 20%</span>
                            <h5 class="description-header">$24,813.53</h5>
                            <span class="description-text">TOTAL PROFIT</span>
                          </div><!-- /.description-block -->
                        </div><!-- /.col -->
                        <div class="col-sm-3 col-xs-6">
                          <div class="description-block">
                            <span class="description-percentage text-red"><i class="fa fa-caret-down"></i> 18%</span>
                            <h5 class="description-header">1200</h5>
                            <span class="description-text">GOAL COMPLETIONS</span>
                          </div><!-- /.description-block -->
                        </div>
                      </div><!-- /.row -->
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--Graph data blok son-->

            <!--Sales dashboard data ilk blok-->
            <div class="row">
            <div class="col-md-3 col-sm-6 col-xs-12 " ">
                <!--<div class="flipper" >-->
                    <div class="info-box overlay front">
                  
                    <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>
                    <div class="info-box-content" id="toplam_sales_1_container">
                        <h3>
                            <div class="overlay" >
                                <i class="fa fa-refresh fa-spin" ></i>
                            </div>
                        </h3>
                      <span class="info-box-text info-box-text-fatura"></span>
                      <span class="info-box-number" lang="en">MTBTR sales</span>

                    </div><!-- /.info-box-content -->
                  </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-red"><i class="ion ion-ios-information"></i></span>
                <div class="info-box-content" id="toplam_sales_2_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                    </h3>
                  <span class="info-box-text info-box-text-fatura"></span>
                  <span class="info-box-number" lang="en">MTBTR stocks</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-green"><i class="fa fa-gears "></i></span>
                <div class="info-box-content" id="toplam_sales_3_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                  </h3>
                  <span class="info-box-text info-box-text-fatura"></span>
                  <a id="detay_acilan_bayi_stoklari" style="cursor: pointer;" class="small-box-footer">
                    <i class="fa fa-arrow-circle-right"></i>
                    <span class="info-box-number" style="display: inline;" lang="en">Dealer stocks</span> 
                  </a>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
            <div class="col-md-3 col-sm-6 col-xs-12">
              <div class="info-box">
                <span class="info-box-icon bg-yellow"><i class="ion ion ion-android-time"></i></span>
                <div class="info-box-content" id="toplam_sales_4_container">
                  <h3>
                        <div class="overlay" >
                            <i class="fa fa-refresh fa-spin" ></i>
                        </div>
                  </h3>
                  <span class="info-box-text info-box-text-fatura" ></span>
                  <span class="info-box-number" lang="en">Dealer invoices</span>
                </div><!-- /.info-box-content -->
              </div><!-- /.info-box -->
            </div><!-- /.col -->
          </div>
            <!--Sales dashboard data ilk blok son-->
            
            <!--hidden data block 4 -->
            <div class="row">
                <!--<section class="col-lg-7 connectedSortable">-->
                <div class="col-md-12">
                  <div class="box" id="panel_hidden4" style="display: none;">
                    <div class="box-header with-border">
                      <h3 class="box-title" id="panel_hidden4_title">Bayi Stokları</h3>
                      <div class="box-tools pull-right">
                        <!--<button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>-->
                        <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                      </div>
                    </div><!-- /.box-header -->
                    <div class="box-body" style="display: block;">
                      <div class="row">
                        <div class="col-md-12">
                          
                          <div id="container_hidden_block4" style="min-width: 200px;  margin: 0 auto"></div>
                          
                        </div><!-- /.col -->
                      </div><!-- /.row -->
                    </div><!-- ./box-body -->
                    <div class="box-footer" style="display: block;">
                    </div><!-- /.box-footer -->
                  </div><!-- /.box -->
                </div>
            <!--</section>  -->
            </div>
            <!--hidden data block 4 son-->
            
            <!-- sales dashboard data ikinci blok -->
             <div class="row">
                <div class="col-lg-6 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_sales_block2_1_container" class="small-box bg-aqua">
                        <div class="inner">
                            <h3><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Dealer oppurtunities</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-pie-graph"></i>
                        </div>
                        <a onclick="return false;" class="small-box-footer"><i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
                <div class="col-lg-6 col-xs-6">
                    <!-- small box -->
                    <div id="toplam_sales_block2_2_container" class="small-box bg-green">
                        <div class="inner">
                            <h3><div class="overlay" >
                                    <i class="fa fa-refresh fa-spin" ></i>
                                </div>
                            </h3>
                            <p lang="en">Dealer activities(today)</p>
                        </div>
                        <div class="icon">
                            <i class="ion ion-person-add"></i>
                        </div>
                        <a onclick="return false;" class="small-box-footer"><i class="fa fa-arrow-circle-right"></i></a>
                    </div>
                </div><!-- ./col -->
            </div><!-- /.row -->
            <!-- sales dashboard data ikinci blok son -->
            
            <!-- Main row -->
            <div class="row">
            
                <section class="col-lg-6 connectedSortable">
                    
                    <!-- TO DO List -->
                    <div id='todolistboxServis' class="box box-primary">
                        <div class="box-header">
                            <i class="ion ion-clipboard"></i>
                            <h3 class="box-title" lang="en">Last orders <span lang="en">Dealer</span></h3>
                            <div class="box-tools pull-right">
                                 <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                 <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div><!-- /.box-header -->
                        <div class="box-body" id="loader_test">
                            <ul class="todo-list" id="servisFillerUL">
                                <li>
                                    <!-- drag handle -->
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!-- checkbox -->
                                    <input type="checkbox" value="" name=""/>
                                    <!-- todo text -->
                                    <span data-fill="true" class="text">test</span>
                                    <!-- Emphasis label -->
                                    <small data-fill-number="true" class="label label-danger"><i class="fa fa-clock-o"></i> </small>
                                    <!-- General tools such as edit or delete-->
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span  data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-info"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">   
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-warning"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-success"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-primary"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <input type="checkbox" value="" name=""/>
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-default"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                            </ul>
                        </div><!-- /.box-body -->
                        <div class="box-footer clearfix no-border">
                            <!--<button class="btn btn-default pull-right"><i class="fa fa-plus"></i> Ekle</button>-->
                        </div>
                    </div><!-- /.box -->

                    <!-- quick email widget -->
                    <div class="box box-info">
                        <div class="box-header">
                            <i class="fa fa-envelope"></i>
                            <h3 class="box-title" lang="en">Email</h3>
                            <!-- tools box -->
                            <div class="pull-right box-tools">
                                <button class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
                            </div><!-- /. tools -->
                        </div>
                        <div class="box-body">
                            <form action="#" method="post">
                                <div class="form-group">
                                    <input type="email" lang="en" class="form-control" name="Kime" placeholder="to who"/>
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" name="Konu" lang="en" placeholder="subject"/>
                                </div>
                                <div>
                                    <textarea class="textarea" lang="en" placeholder="message" style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                </div>
                            </form>
                        </div>
                        <div class="box-footer clearfix">
                            <button class="pull-right btn btn-default" id="sendEmail" lang="en">Send<i class="fa fa-arrow-circle-right"></i></button>
                        </div>
                    </div>


                </section><!-- /.Left col -->
                <!-- right col (We are only adding the ID to make the widgets sortable)-->
                <section class="col-lg-6 connectedSortable">

                    <!-- TO DO List -->
                    <div id='todolistboxServisMusteri' class="box box-primary">
                        <div class="box-header">
                            <i class="ion ion-clipboard"></i>
                            <h3 class="box-title" lang="en">Last orders <span lang="en">Customer</span></h3>
                            <div class="box-tools pull-right">
                                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                            </div>
                        </div><!-- /.box-header -->
                        <div class="box-body">
                            <ul class="todo-list" id="servisMusteriFillerUL">
                                <li>
                                    <!-- drag handle -->
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!-- checkbox -->
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <!-- todo text -->
                                    <span data-fill="true" class="text"></span>
                                    <!-- Emphasis label -->
                                    <small data-fill-number="true" class="label label-danger"><i class="fa fa-clock-o"></i> </small>
                                    <!-- General tools such as edit or delete-->
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span  data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-info"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">   
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-warning"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-success"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-primary"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                                <li>
                                    <span class="handle">
                                        <i class="fa fa-ellipsis-v"></i>
                                        <i class="fa fa-ellipsis-v"></i>
                                    </span>
                                    <!--<input type="checkbox" value="" name=""/>-->
                                    <span data-fill="true" class="text"></span>
                                    <small data-fill-number="true" class="label label-default"><i class="fa fa-clock-o"></i> </small>
                                    <div class="tools">
                                        <i class="fa fa-edit"></i>
                                        <i class="fa fa-trash-o"></i>
                                    </div>
                                </li>
                            </ul>
                        </div><!-- /.box-body -->
                        <div class="box-footer clearfix no-border">
                            <!--<button class="btn btn-default pull-right"><i class="fa fa-plus"></i> Ekle</button>-->
                        </div>
                    </div>
                    
                    <!-- Map box -->
                    <div class="box box-solid bg-light-blue-gradient">
                        <div class="box-header">
                            <!-- tools box -->
                            <div class="pull-right box-tools">
                              <!--<button class="btn btn-primary btn-sm daterange pull-right" data-toggle="tooltip" title="Date range"><i class="fa fa-calendar"></i></button>-->
                                <button class="btn btn-primary btn-sm pull-right" data-widget='collapse' data-toggle="tooltip" title="Collapse" style="margin-right: 5px;"><i class="fa fa-minus"></i></button>
                            </div><!-- /. tools -->

                            <i class="fa fa-map-marker"></i>
                            <h3 class="box-title">
                                <!--Üye Ülkeler-->
                            </h3>
                        </div>
                        <div class="box-body">
                            <div id="world-map" style="height: 250px; width: 100%;"></div>
                        </div><!-- /.box-body-->
                        <div class="box-footer no-border">
                            <div class="row">
                                <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                                    <div id="sparkline-1"></div>
                                    <div class="knob-label"><!--OSB Imalat verileri...--></div>
                                </div><!-- ./col -->
                                <div class="col-xs-4 text-center" style="border-right: 1px solid #f4f4f4">
                                    <div id="sparkline-2"></div>
                                    <div class="knob-label"><!--OSB Imalat verileri...--></div>
                                </div><!-- ./col -->
                                <div class="col-xs-4 text-center">
                                    <div id="sparkline-3"></div>
                                    <div class="knob-label"><!--OSB Imalat verileri...--></div>
                                </div><!-- ./col -->
                            </div><!-- /.row -->
                        </div>
                    </div>
                    <!-- /.box -->

                </section><!-- right col -->
            </div><!-- /.row (main row) -->

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
    <!-- footer --> 
    <?php echo $this->partial('partials/adminfooterpartial.phtml'); ?>
    <!-- footerson--> 

    <!-- Control Sidebar --> 
    <?php echo $this->partial('partials/admincontrolasidepartial.phtml'); ?>
    <!-- Control Sidebar son-->   
    
</div><!-- ./wrapper -->
<!-- sayfa içine yazılan js'ler ekleniyor-->
<script src="<?php echo $this->basePath('jsinline/admin.js') ?>" type="text/javascript"></script>
